Repository splunk/addonfactory-ucc-generator, pull requests merged in 2024-11, with the labels that each got.

#1414 docs: update order list prefix and add lint
  .markdownlint.yaml
  docs/contributing.md
  docs/entity/components.md
  docs/openapi.md
  ui/README.md
Labels: documentation, size/M

#1427 ci: add expected failure for appinspect-api check
  tests/testdata/expected_addons/expected_output_global_config_everything/.appinspect_api.expect.yaml
Labels: github_actions, size/XS

#1435 chore(quick_start_ui.sh): fix container name
  scripts/quick_start_ui.sh
Labels: size/XS

#1434 docs(contributing): update commands for building TA
  docs/contributing.md
Labels: documentation, size/S

#1428 test(ui): check showing network error
  ui/src/pages/Configuration/tests/ConfigurationPage.test.tsx
Labels: javascript, size/S

#1429 test(delete-modal): add network error test case
  ui/src/components/DeleteModal/DeleteModal.test.tsx
  ui/src/components/DeleteModal/DeleteModal.tsx
Labels: javascript, size/M

#1436 test(selectors): add numeric values
  ui/src/components/table/CustomTableRow.jsx
  ui/src/pages/Configuration/stories/ConfigurationPage.stories.tsx
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-configuration-view-add-chromium.png
  ui/src/pages/Configuration/stories/globalConfig.json
  ui/src/pages/Input/stories/InputPage.stories.tsx
  ui/src/pages/Input/stories/__images__/InputPage-input-page-expanded-row-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-add-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-update-input-chromium.png
  ui/src/pages/Input/stories/globalConfig.json
Labels: javascript, size/L

#1438 test(coverage): exclude untestable types from coverage
  ui/jest.config.ts
Labels: size/XS

#1433 docs: add the print page
  .markdownlint.yaml
  .markdownlintignore
  docs/advanced/custom_mapping.md
  docs/advanced/custom_warning.md
  docs/advanced/dependent_dropdown.md
  docs/advanced/groups_feature.md
  docs/advanced/oauth_support.md
  docs/advanced/os-dependent_libraries.md
  docs/advanced/save_validator.md
  docs/advanced/sub_description.md
  docs/alert_actions/adaptive_response.md
  docs/alert_actions/alert_scripts.md
  docs/alert_actions/index.md
  docs/configurations/index.md
  docs/configurations/logging.md
  docs/configurations/proxy.md
  docs/custom_ui_extensions/custom_cell.md
  docs/custom_ui_extensions/custom_control.md
  docs/custom_ui_extensions/custom_hook.md
  docs/custom_ui_extensions/custom_menu.md
  docs/custom_ui_extensions/custom_row.md
  docs/custom_ui_extensions/custom_tab.md
  docs/custom_ui_extensions/overview.md
  docs/entity/index.md
  docs/entity/modifyFieldsOnValue.md
  docs/entity/validators.md
  docs/generated_files.md
  docs/inputs/helper.md
  docs/inputs/index.md
  docs/inputs/multilevel_menu.md
  docs/inputs/tabs.md
  docs/metadata.md
  docs/table.md
  docs/theme_overrides/partials/header.html
  docs/ui_tests_alert_actions_page.md
  docs/ui_tests_config_page_account.md
  docs/ui_tests_config_page_custom.md
  docs/ui_tests_config_page_general.md
  docs/ui_tests_config_page_logging.md
  docs/ui_tests_config_page_proxy.md
  docs/ui_tests_inputs_page.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
  splunk_add_on_ucc_framework/generators/doc_generator.py
  tests/smoke/__init__.py
  tests/unit/__init__.py
  tests/unit/generators/test_doc_generator.py
Labels: size/L

#1393 docs: reorganize quickstart and home pages
  docs/commands.md
  docs/dot_conf_files.md
  docs/generated_files.md
  docs/index.md
  docs/quickstart.md
  mkdocs.yml
Labels: size/L

#1449 docs(generated_files): update generation script
  .github/workflows/automatic_doc_generation.yml
  docs/generated_files.md
  splunk_add_on_ucc_framework/generators/doc_generator.py
  tests/unit/generators/test_doc_generator.py
Labels: size/S

#1439 fix(Dropdown): fix showing selected option when value is numeric
  ui/src/components/MultiInputComponent/MultiInputComponent.test.tsx
  ui/src/components/MultiInputComponent/MultiInputComponent.tsx
  ui/src/components/SingleInputComponent/SingleInputComponent.test.tsx
  ui/src/components/SingleInputComponent/SingleInputComponent.tsx
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-configuration-view-add-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-add-chromium.png
  ui/src/pages/Input/stories/globalConfig.json
Labels: size/L

#1424 refactor: remove axios dependency
  ui/package.json
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/ConfigurationFormView.jsx
  ui/src/components/DeleteModal/DeleteModal.tsx
  ui/src/components/MultiInputComponent/MultiInputComponent.tsx
  ui/src/components/SingleInputComponent/SingleInputComponent.tsx
  ui/src/components/table/TableWrapper.tsx
  ui/src/util/ResponseError.ts
  ui/src/util/api.test.ts
  ui/src/util/api.ts
  ui/src/util/axiosCallWrapper.ts
  ui/src/util/messageUtil.test.ts
  ui/src/util/messageUtil.ts
  ui/src/util/script.ts
  ui/src/util/util.ts
  ui/yarn.lock
Labels: javascript, size/XL

#1156 test(smoke): fix path to globalConfig (incorrect file was used)
  tests/smoke/test_ucc_build.py
Labels: size/S

#1454 tests: added test cases for enable action
  tests/unit/test_global_config_update.py
  tests/unit/testdata/valid_config_input_with_enable_action.json
Labels: tests, size/L

#1452 chore(pyproject): explicitly specify supported Python versions
  .github/workflows/build-test-release.yml
  poetry.lock
  pyproject.toml
Labels: size/S

#1446 docs(contributing): add development guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  docs/contributing.md
Labels: size/S

#1432 feat: add grouping to configuration page
  docs/configurations/index.md
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  ui/src/components/BaseFormView/BaseFormConfigMock.ts
  ui/src/components/BaseFormView/BaseFormView.test.tsx
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-config-page-groups-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-input-page-groups-chromium.png
  ui/src/types/globalConfig/pages.ts
Labels: javascript, size/L

#1415 feat: deprecate .uccignore and upgrade additional_package
  .gitignore
  docs/additional_packaging.md
  docs/uccignore.md
  splunk_add_on_ucc_framework/commands/build.py
  tests/smoke/test_ucc_build.py
  tests/testdata/test_addons/package_global_config_everything_uccignore/.uccignore
  tests/testdata/test_addons/package_global_config_everything_uccignore/additional_packaging.py
  tests/testdata/test_addons/package_global_config_everything_uccignore/package/default/nav/views/file_copied_from_source_code.xml
  tests/testdata/test_addons/package_global_config_everything_uccignore/package/default/redundant.conf
Labels: enhancement, deprecation, size/L

#1451 fix(table): custom mapping for values in Status column
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
  ui/src/components/ControlWrapper/ControlWrapper.tsx
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/components/CustomControl/CustomControlMockForTest.ts
  ui/src/components/FormModifications/FormModifications.test.tsx
  ui/src/components/FormModifications/FormModifications.ts
  ui/src/components/table/CustomTable.tsx
  ui/src/components/table/CustomTableRow.tsx
  ui/src/components/table/stories/TableWrapper.stories.tsx
  ui/src/components/table/stories/__images__/TableWrapper-simple-config-with-status-mapped-chromium.png
  ui/src/components/table/stories/__images__/TableWrapper-simple-table-style-page-chromium.png
  ui/src/components/table/stories/configMockups.ts
  ui/src/components/table/stories/rowDataMockup.ts
  ui/src/components/table/table.utils.ts
  ui/src/components/table/tests/CustomTableRow.test.tsx
  ui/src/components/table/tests/TableWrapper.test.tsx
  ui/src/hooks/usePlatform.ts
  ui/src/types/components/BaseFormTypes.ts
Labels: javascript, size/L

#1447 feat: add ability to provide custom pip flags
  docs/commands.md
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/install_python_libraries.py
  splunk_add_on_ucc_framework/main.py
  tests/unit/test_install_python_libraries.py
  tests/unit/test_main.py
Labels: size/L

#1458 Revert "ci: add expected failure for appinspect-api check"
  tests/testdata/expected_addons/expected_output_global_config_everything/.appinspect_api.expect.yaml
Labels: size/XS

#1457 chore(pull request template): add PR type
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S

#1462 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
Labels: size/XXL

#1463 fix(select): fetching options when some dependency is null
  ui/src/components/SingleInputComponent/SingleInputComponent.test.tsx
  ui/src/util/api.ts
Labels: size/M

#1464 chore: merge develop into main
  .github/workflows/build-test-release.yml
  poetry.lock
  pyproject.toml
  ui/src/components/SingleInputComponent/SingleInputComponent.test.tsx
  ui/src/util/api.ts
Labels: size/L

#1465 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
Labels: size/S

#1430 feat(inputs): show input services status count
  docs/images/inputs/Tabs_Output.png
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-input-page-view-chromium.png
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-required-view-chromium.png
  ui/src/components/table/TableHeader.jsx
  ui/src/components/table/stories/__images__/TableWrapper-ouath-basic-chromium.png
  ui/src/components/table/stories/__images__/TableWrapper-simple-config-with-status-mapped-chromium.png
  ui/src/components/table/stories/__images__/TableWrapper-simple-table-style-page-chromium.png
  ui/src/components/table/stories/rowDataMockup.ts
  ui/src/components/table/tests/TableWrapper.test.tsx
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-configuration-page-view-chromium.png
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-configuration-view-add-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-expanded-row-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-add-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-update-input-chromium.png
  ui/src/pages/stories/__images__/GlobalConfigPlayground-global-config-playground-chromium.png
Labels: javascript, size/L

#1467 test(SingleInputComponent): add expect and fix warning
  ui/.eslintrc.js
  ui/src/components/SingleInputComponent/SingleInputComponent.test.tsx
Labels: size/S

#1440 test: verify console logs in UI tests
  tests/ui/conftest.py
Labels: size/M

#1470 test(TableExpansionRow): add reproduction with stale values for Expansion Row
  ui/src/components/table/stories/configMockups.ts
  ui/src/components/table/tests/TableExpansionRow.test.tsx
Labels: size/L

#1455 test(smoke): update smoke tests to cover more scenario
  docs/additional_packaging.md
  splunk_add_on_ucc_framework/commands/build.py
  tests/smoke/test_ucc_build.py
  tests/testdata/test_addons/package_global_config_everything/additional_packaging.py
  tests/testdata/test_addons/package_global_config_everything_uccignore/additional_packaging.py
Labels: size/M

#1473 docs(changelog): fix headers consistency (#1466)
  .releaserc
  docs/CHANGELOG.md
Labels: size/L

#1474 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/src/components/MultiInputComponent/MultiInputComponent.tsx
  ui/src/components/SingleInputComponent/SingleInputComponent.tsx
  ui/src/util/api.test.tsx
  ui/src/util/api.ts
Labels: size/M

#1469 feat: do not create __pycache__ in lib dir
  splunk_add_on_ucc_framework/install_python_libraries.py
  tests/smoke/test_ucc_build.py
  tests/unit/test_install_python_libraries.py
Labels: size/M

#1445 fix: display newest information in row more info section
  ui/src/components/table/CustomTableControl.jsx
  ui/src/components/table/tests/TableExpansionRow.test.tsx
Labels: javascript, size/L

#1481 chore(smartx): update to 5.3.1
  poetry.lock
  pyproject.toml
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/ui/test_configuration_page_account_tab.py
  tests/ui/test_input_page.py
Labels: size/S

#1475 feat: add license during init command
  .gitignore
  docs/commands.md
  splunk_add_on_ucc_framework/commands/init.py
  splunk_add_on_ucc_framework/main.py
  splunk_add_on_ucc_framework/templates/Licenses/Apache License 2.0.txt
  splunk_add_on_ucc_framework/templates/Licenses/MIT License.txt
  splunk_add_on_ucc_framework/templates/Licenses/SPLUNK PRE-RELEASE SOFTWARE LICENSE AGREEMENT.txt
  splunk_add_on_ucc_framework/templates/app.manifest.init-template
  splunk_add_on_ucc_framework/utils.py
  tests/smoke/test_ucc_init.py
  tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/LICENSE.txt
  tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/LICENSES/MIT License.txt
  tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/app.manifest
  tests/testdata/expected_addons/expected_files_conflict_test/expected_log.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/LICENSES/Apache License 2.0.txt
  tests/testdata/test_addons/package_files_conflict_test/package/LICENSES/LICENSE.txt
  tests/testdata/test_addons/package_global_config_everything/package/LICENSES/Apache License 2.0.txt
  tests/testdata/test_addons/package_global_config_everything_uccignore/LICENSES/Apache-2.0.txt
  tests/testdata/test_addons/package_global_config_everything_uccignore/package/LICENSES/Apache License 2.0.txt
  tests/unit/commands/test_init.py
  tests/unit/test_main.py
  tests/unit/test_utils.py
Labels: enhancement, size/L

#1479 chore(coverage): bump from 81 to 81.5
  .coveragerc
Labels: size/XS

#1484 fix: allow packaging from 23.0
  poetry.lock
  pyproject.toml
Labels: size/XS

#1471 test(TableWrapper): remove mocking immutability-helper dep
  ui/jest.polyfills.ts
  ui/src/components/DeleteModal/DeleteModal.test.tsx
  ui/src/components/table/tests/TableWrapper.test.tsx
Labels: javascript, size/XS

#1486 docs: minor changes
  README.md
  docs/index.md
  docs/quickstart.md
Labels: size/S

#1487 chore(renovate): ignore python update
  renovate.json
Labels: size/XS

#1482 fix: support Windows when checking library version
  splunk_add_on_ucc_framework/install_python_libraries.py
  tests/unit/test_install_python_libraries.py
Labels: size/M

#1488 chore(renovate): ignore mkdocs update
  renovate.json
Labels: size/S

#1489 fix: required star visibility when using modify prop
  ui/src/components/ControlWrapper/ControlWrapper.tsx
  ui/src/components/ControlWrapper/stories/ControlWrapper.stories.ts
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-with-modifications-chromium.png
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-with-modifications-make-required-chromium.png
  ui/src/components/ControlWrapper/test/ControlWrapper.test.tsx
Labels: size/L

#1491 chore(appinspect-api): make it pass
  .github/workflows/build-test-release.yml
  tests/testdata/expected_addons/expected_output_global_config_everything/.appinspect_api.expect.yaml
  tests/testdata/test_addons/package_global_config_everything/package/app.manifest
Labels: size/XS

#1492 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
Labels: size/XL

#1493 docs: highlight underscores as code block
  docs/CHANGELOG.md
Labels: size/XS
