Repository splunk/addonfactory-ucc-generator, pull requests merged in 2024-12, with the labels that each got.

#1483 feat: add author during init
  docs/commands.md
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/commands/init.py
  splunk_add_on_ucc_framework/main.py
  splunk_add_on_ucc_framework/templates/app.manifest.init-template
  splunk_add_on_ucc_framework/utils.py
  tests/smoke/test_ucc_init.py
  tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/app.manifest
  tests/unit/commands/test_init.py
  tests/unit/test_main.py
  tests/unit/test_utils.py
Labels: enhancement, size/L

#1500 fix: group elements use all functionalities
  ui/src/components/BaseFormView/BaseFormConfigMock.ts
  ui/src/components/BaseFormView/BaseFormView.test.tsx
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/BaseFormViewGrups.test.tsx
  ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-group-modifications-config-chromium.png
Labels: size/L

#1494 feat(modifyFieldsOnValue): enable field to modify itself
  docs/entity/modifyFieldsOnValue.md
  splunk_add_on_ucc_framework/global_config_validator.py
  tests/unit/test_global_config_validator.py
  tests/unit/testdata/invalid_config_with_modification_circular_modifications.json
  tests/unit/testdata/invalid_config_with_modification_for_field_itself.json
  tests/unit/testdata/valid_config_with_modification_on_value_change.json
  ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-field-modify-itself-after-mods-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-field-modify-itself-chromium.png
  ui/src/components/BaseFormView/tests/BaseFormView.test.tsx
  ui/src/components/BaseFormView/tests/BaseFormViewModifications.test.tsx
  ui/src/components/BaseFormView/tests/configMocks.ts
Labels: size/L

#1502 chore: dimmed as default disable method
  ui/jest.setup.ts
  ui/package.json
  ui/src/components/AcceptModal/AcceptModal.tsx
  ui/src/components/ConfigurationFormView.jsx
  ui/src/components/DashboardInfoModal/DashboardInfoModal.tsx
  ui/src/components/DeleteModal/DeleteModal.tsx
  ui/src/components/EntityModal/EntityModal.test.tsx
  ui/src/components/EntityModal/EntityModal.tsx
  ui/src/components/EntityPage/EntityPage.tsx
  ui/src/components/ErrorModal/ErrorModal.tsx
  ui/src/components/FormModifications/FormModifications.test.tsx
  ui/src/components/MenuInput/MenuInput.tsx
  ui/src/components/MultiInputComponent/MultiInputComponent.test.tsx
  ui/src/components/TextComponent/TextComponent.tsx
  ui/src/components/TextComponent/stories/TextComponent.stories.tsx
  ui/src/components/TextComponent/stories/__images__/TextComponent-all-props-true-chromium.png
  ui/src/components/UCCButton/UCCButton.tsx
  ui/src/components/table/TableHeader.jsx
  ui/src/pages/Dashboard/DataIngestionModal.tsx
  ui/src/tests/expectExtenders.ts
  ui/src/types/modules.d.ts
  ui/yarn.lock
Labels: size/L

#1505 chore: merge develop into main
  docs/CHANGELOG.md
  docs/commands.md
  docs/entity/modifyFieldsOnValue.md
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/commands/init.py
  splunk_add_on_ucc_framework/global_config_validator.py
  splunk_add_on_ucc_framework/main.py
  splunk_add_on_ucc_framework/templates/app.manifest.init-template
  splunk_add_on_ucc_framework/utils.py
  tests/smoke/test_ucc_init.py
  tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/app.manifest
  tests/unit/commands/test_init.py
  tests/unit/test_global_config_validator.py
  tests/unit/test_main.py
  tests/unit/test_utils.py
  tests/unit/testdata/invalid_config_with_modification_circular_modifications.json
  tests/unit/testdata/invalid_config_with_modification_for_field_itself.json
  tests/unit/testdata/valid_config_with_modification_on_value_change.json
  ui/jest.setup.ts
  ui/package.json
  ui/src/components/AcceptModal/AcceptModal.tsx
  ui/src/components/BaseFormView/BaseFormConfigMock.ts
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/BaseFormViewGrups.test.tsx
  ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-field-modify-itself-after-mods-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-field-modify-itself-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-group-modifications-config-chromium.png
  ui/src/components/BaseFormView/tests/BaseFormView.test.tsx
  ui/src/components/BaseFormView/tests/BaseFormViewModifications.test.tsx
  ui/src/components/BaseFormView/tests/configMocks.ts
  ui/src/components/ConfigurationFormView.jsx
  ui/src/components/DashboardInfoModal/DashboardInfoModal.tsx
  ui/src/components/DeleteModal/DeleteModal.tsx
  ui/src/components/EntityModal/EntityModal.test.tsx
  ui/src/components/EntityModal/EntityModal.tsx
  ui/src/components/EntityPage/EntityPage.tsx
  ui/src/components/ErrorModal/ErrorModal.tsx
  ui/src/components/FormModifications/FormModifications.test.tsx
  ui/src/components/MenuInput/MenuInput.tsx
  ui/src/components/MultiInputComponent/MultiInputComponent.test.tsx
  ui/src/components/TextComponent/TextComponent.tsx
  ui/src/components/TextComponent/stories/TextComponent.stories.tsx
  ui/src/components/TextComponent/stories/__images__/TextComponent-all-props-true-chromium.png
  ui/src/components/UCCButton/UCCButton.tsx
  ui/src/components/table/TableHeader.jsx
  ui/src/pages/Dashboard/DataIngestionModal.tsx
  ui/src/tests/expectExtenders.ts
  ui/src/types/modules.d.ts
  ui/yarn.lock
Labels: size/XXL

#1506 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
Labels: size/L

#1499 fix: rest handler template code for oauth
  splunk_add_on_ucc_framework/templates/oauth.template
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_oauth.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_oauth.py
  tests/testdata/test_addons/package_global_config_everything/package/lib/requirements.txt
Labels: size/S

#1507 feat: add default validators
  splunk_add_on_ucc_framework/templates/globalConfig.json.init-template
  tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/globalConfig.json
Labels: size/M
