Repository splunk/addonfactory-ucc-generator, pull requests merged in 2024-04, with the labels that each got.

#1115 feat(code): add custom validators for account configs
  docs/advanced/custom_rest_handler.md
  splunk_add_on_ucc_framework/commands/rest_builder/global_config_builder_schema.py
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_validate_account_rh.py
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/package/bin/splunk_ta_uccexample_validate_account_rh.py
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/unit/commands/rest_builder/test_global_config_builder_schema.py
  tests/unit/testdata/valid_config.json
Labels: enhancement, python

#1131 feat(CheckboxGroup): add support for required field
  splunk_add_on_ucc_framework/schema/schema.json
  tests/unit/testdata/valid_config.json
  ui/src/components/BaseFormView.tsx
  ui/src/components/CheckboxGroup/checkboxGroupRequiredMocks.json
  ui/src/components/CheckboxGroup/stories/CheckboxGroupInputPage.stories.tsx
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-required-view-chromium.png
Labels: enhancement

#1134 feat: add iconFileName for alert action
  splunk_add_on_ucc_framework/commands/modular_alert_builder/alert_actions_conf_gen.py
  splunk_add_on_ucc_framework/commands/modular_alert_builder/alert_actions_merge.py
  splunk_add_on_ucc_framework/commands/modular_alert_builder/builder.py
  splunk_add_on_ucc_framework/schema/schema.json
  tests/smoke/helpers.py
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/alert_actions.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/test icon.png
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/alert_actions.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/data/ui/alerts/test_alert.html
  tests/testdata/test_addons/package_files_conflict_test/globalConfig.json
  tests/testdata/test_addons/package_global_config_configuration/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/package/appserver/static/test icon.png
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything_uccignore/package/appserver/static/test icon.png
  tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
  tests/testdata/test_addons/package_global_config_only_one_tab/globalConfig.json
  tests/ui/test_alert_actions_page.py
  tests/unit/commands/modular_alert_builder/test_alert_actions_conf_gen.py
Labels: enhancement

#1133 docs: add detailed docs for alert action
  docs/alert_actions/adaptive_response.md
  docs/alert_actions/alert_scripts.md
  docs/alert_actions/index.md
  docs/images/alert_actions/alert_output.png
  docs/index.md
  mkdocs.yml
Labels: documentation

#1143 fix: add customScript for alert action
  docs/alert_actions/alert_scripts.md
  docs/alert_actions/index.md
  splunk_add_on_ucc_framework/commands/modular_alert_builder/alert_actions_conf_gen.py
  splunk_add_on_ucc_framework/commands/modular_alert_builder/alert_actions_py_gen.py
  splunk_add_on_ucc_framework/commands/modular_alert_builder/arf_template/alert_action.py.template
  splunk_add_on_ucc_framework/schema/schema.json
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/alerticon.png
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/myAlertLogic.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample/modalert_test_alert_helper.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/test_alert.py
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/package/bin/myAlertLogic.py
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
Labels: documentation, enhancement

#1166 test(smoke): update uccignore test case
  tests/smoke/helpers.py
  tests/smoke/test_ucc_build.py
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything_uccignore/package/appserver/static/test icon.png
Labels: tests
