Repository splunk/addonfactory-ucc-generator, pull requests merged in 2024-10, with the labels that each got.

#1335 fix(globalConfig): update name and rest root convention
  .markdownlint.yaml
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/commands/init.py
  splunk_add_on_ucc_framework/schema/schema.json
  splunk_add_on_ucc_framework/templates/input.helper-init-template
  tests/smoke/test_ucc_init.py
  tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/globalConfig.json
  tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/bin/demo_input_helper.py
  tests/unit/commands/test_build.py
  tests/unit/commands/test_init.py
Labels: bug

#1351 chore: follow SemVer guidelines for version in globalConfig
  splunk_add_on_ucc_framework/utils.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
  tests/testdata/test_addons/package_files_conflict_test/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
  tests/testdata/test_addons/package_global_config_only_one_tab/globalConfig.json
  tests/unit/test_utils.py
Labels: bug

#1352 chore: updated versions of dependent libraries
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  tests/ui/pytest.ini
Labels: dependencies

#1387 refactor: remove unused function
  splunk_add_on_ucc_framework/install_python_libraries.py
  tests/unit/test_install_python_libraries.py
Labels: size/M

#1384 refactor(api): encode URL path
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/ConfigurationFormView.jsx
  ui/src/components/DeleteModal/DeleteModal.test.tsx
  ui/src/components/DeleteModal/DeleteModal.tsx
  ui/src/components/MultiInputComponent/MultiInputComponent.tsx
  ui/src/components/SingleInputComponent/SingleInputComponent.tsx
  ui/src/components/table/TableWrapper.tsx
  ui/src/pages/Configuration/tests/ConfigurationPage.test.tsx
  ui/src/types/modules.d.ts
  ui/src/util/__mocks__/util.ts
  ui/src/util/axiosCallWrapper.ts
  ui/src/util/util.ts
Labels: size/L

#1392 fix(CustomControl): change order of function parameters
  docs/custom_ui_extensions/custom_control.md
  ui/src/components/CustomControl.tsx
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/components/CustomControl/CustomControlMockForTest.ts
Labels: size/L

#1394 chore: merge develop into main
  docs/contributing.md
  docs/custom_ui_extensions/custom_control.md
  splunk_add_on_ucc_framework/install_python_libraries.py
  tests/unit/test_install_python_libraries.py
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/ConfigurationFormView.jsx
  ui/src/components/CustomControl.tsx
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/components/CustomControl/CustomControlMockForTest.ts
  ui/src/components/DeleteModal/DeleteModal.test.tsx
  ui/src/components/DeleteModal/DeleteModal.tsx
  ui/src/components/MultiInputComponent/MultiInputComponent.tsx
  ui/src/components/SingleInputComponent/SingleInputComponent.tsx
  ui/src/components/table/TableWrapper.tsx
  ui/src/pages/Configuration/tests/ConfigurationPage.test.tsx
  ui/src/types/modules.d.ts
  ui/src/util/__mocks__/util.ts
  ui/src/util/axiosCallWrapper.ts
  ui/src/util/util.ts
Labels: size/L

#1395 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
Labels: size/S

#1388 ci: run appinspect-api stage for addon used in smoke tests
  .github/workflows/build-test-release.yml
  tests/testdata/expected_addons/expected_output_global_config_everything/.appinspect_api.expect.yaml
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README.txt
  tests/testdata/test_addons/package_global_config_everything/package/README.txt
Labels: github_actions, size/M

#1401 ci: simplify GitHub workflow for caching Yarn deps
  .github/actions/cached-ui-deps/action.yml
  .github/workflows/build-ui.yml
  .github/workflows/docs.yml
  .github/workflows/storybook-visual.yml
Labels: size/S

#1398 refactor(ui-components): remove unused code
  ui/src/components/EntityModal/TestConfig.ts
  ui/src/components/PlaceholderComponent/PlaceholderComponent.tsx
  ui/src/components/PlaceholderComponent/stories/PlaceholderComponent.stories.ts
  ui/src/components/PlaceholderComponent/stories/__images__/PlaceholderComponent-base-chromium.png
  ui/src/components/table/tests/MockedData.ts
Labels: size/L

#1405 chore(renovate): ignore ubuntu updates for GitHub Actions
  renovate.json
Labels: size/XS

#1406 ci: parse node version from package.json
  .github/actions/cached-ui-deps/action.yml
  .github/workflows/build-test-release.yml
  .github/workflows/build-ui.yml
  .github/workflows/docs.yml
  .github/workflows/storybook-visual.yml
Labels: size/S

#1397 docs(contribution): adjust pull requests instructions and add building TA instructions
  docs/contributing.md
Labels: size/L

#1396 docs: add light/dark theme support
  docs/css/extra.css
  mkdocs.yml
Labels: size/S

#1408 docs: update documentation and examples
  docs/advanced/dependent_dropdown.md
  docs/custom_ui_extensions/custom_control.md
  docs/entity/validators.md
Labels: size/L

#1386 fix: remove support for the "enable" action in table inputs
  docs/custom_ui_extensions/custom_menu.md
  docs/custom_ui_extensions/custom_row.md
  docs/inputs/tabs.md
  docs/table.md
  splunk_add_on_ucc_framework/global_config_update.py
  splunk_add_on_ucc_framework/schema/schema.json
  splunk_add_on_ucc_framework/templates/globalConfig.json.init-template
  tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/globalConfig.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
  tests/testdata/test_addons/package_files_conflict_test/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
  tests/testdata/test_addons/package_global_config_only_one_tab/globalConfig.json
  tests/unit/testdata/config_with_biased_terms.json
  tests/unit/testdata/invalid_config_both_rest_handler_name_class_are_present.json
  tests/unit/testdata/invalid_config_both_rest_handler_name_module_are_present.json
  tests/unit/testdata/invalid_config_checkbox_groups_duplicate_field_in_options_groups.json
  tests/unit/testdata/invalid_config_checkbox_groups_duplicate_fields_in_options_rows.json
  tests/unit/testdata/invalid_config_checkbox_groups_undefined_field_used_in_groups.json
  tests/unit/testdata/invalid_config_inputs_autoCompleteFields_duplicates.json
  tests/unit/testdata/invalid_config_inputs_children_duplicates.json
  tests/unit/testdata/invalid_config_inputs_entity_duplicates.json
  tests/unit/testdata/invalid_config_inputs_multilevel_menu_duplicate_groups.json
  tests/unit/testdata/invalid_config_inputs_multilevel_menu_invalid_groupname_or_grouptitle.json
  tests/unit/testdata/invalid_config_inputs_multilevel_menu_invalid_groupservices.json
  tests/unit/testdata/invalid_config_inputs_number_validator_range_second_element_smaller_than_first.json
  tests/unit/testdata/invalid_config_inputs_number_validator_range_should_have_2_elements.json
  tests/unit/testdata/invalid_config_inputs_regex_validator_non_compilable_pattern.json
  tests/unit/testdata/invalid_config_inputs_services_duplicates.json
  tests/unit/testdata/invalid_config_inputs_string_validator_maxLength_less_than_minLength.json
  tests/unit/testdata/invalid_config_no_configuration_tabs.json
  tests/unit/testdata/invalid_config_no_configuration_tabs.yaml
  tests/unit/testdata/invalid_config_only_rest_handler_class_is_present.json
  tests/unit/testdata/invalid_config_only_rest_handler_module_is_present.json
  tests/unit/testdata/valid_config.json
  tests/unit/testdata/valid_config.yaml
  tests/unit/testdata/valid_config_logging_tab_not_migrated.json
  ui/src/components/BaseFormView/BaseFormConfigMock.ts
  ui/src/components/BaseFormView/stories/globalConfigs/configPageOauth.ts
  ui/src/components/table/stories/configMockups.ts
  ui/src/mocks/globalConfigMock.ts
  ui/src/pages/Configuration/stories/globalConfig.json
  ui/src/pages/Configuration/tests/mockConfigs.ts
  ui/src/pages/Input/stories/globalConfig.json
  ui/src/pages/Input/tests/mockConfigs.ts
  ui/src/pages/stories/globalConfig/exampleOfGlobalConfig.json
  ui/src/pages/stories/globalConfig/globalConfig.json
  ui/src/types/globalConfig/pages.ts
Labels: size/L

#1407 fix: generate basic authentication fields for OpenAPI integration
  docs/openapi.md
  splunk_add_on_ucc_framework/commands/openapi_generator/ucc_to_oas.py
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/appserver/static/openapi.json
  tests/unit/commands/openapi_generator/test_ucc_to_oas.py
  tests/unit/conftest.py
  tests/unit/testdata/openapi.json.multiple_account.generated
  tests/unit/testdata/openapi.json.valid_config.generated
  tests/unit/testdata/valid_config_multiple_account.json
Labels: bug, size/XXL

#1412 feat: require splunktaucclib 6.4.0 during the build phase
  splunk_add_on_ucc_framework/install_python_libraries.py
  tests/unit/test_install_python_libraries.py
Labels: size/M

#1418 docs: fix warning panels
  docs/advanced/oauth_support.md
  docs/entity/index.md
Labels: size/S

#1420 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
Labels: size/M

#1416 chore: single select with default empty string value
  ui/src/components/ControlWrapper/ControlWrapper.tsx
  ui/src/components/SingleInputComponent/SingleInputComponent.tsx
Labels: size/S

#1422 refactor: add types for Splunk utils modules
  ui/src/types/modules.d.ts
Labels: size/M

#1423 refactor(types): allow to parse unknown errors
  ui/jest.config.ts
  ui/src/util/messageUtil.test.ts
  ui/src/util/messageUtil.ts
Labels: size/L
