Repository splunk/addonfactory-ucc-generator, pull requests merged in 2025-09, with the labels that each got.

#1893 feat: build ui from ucc-gen build
  docs/commands.md
  docs/custom_ui_extensions/context/custom_project_init.md
  docs/custom_ui_extensions/context/custom_test_ui_command.md
  docs/custom_ui_extensions/context/overview.md
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/main.py
  tests/unit/test_main.py
Labels: size/L

#1904 chore: resolve merge conflicts of ucc-6-0-0 branch
  docs/configurations/index.md
  docs/inputs/index.md
  docs/options/rest_handlers.md
  docs/quickstart.md
  splunk_add_on_ucc_framework/auto_gen_comparator.py
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/commands/rest_builder/global_config_builder_schema.py
  splunk_add_on_ucc_framework/commands/rest_builder/user_defined_rest_handlers.py
  splunk_add_on_ucc_framework/generators/conf_files/create_restmap_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_web_conf.py
  splunk_add_on_ucc_framework/global_config.py
  splunk_add_on_ucc_framework/schema/schema.json
  splunk_add_on_ucc_framework/templates/conf_files/restmap_conf.template
  splunk_add_on_ucc_framework/templates/web_conf.template
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_addon_no_configuration/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/web.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_organization.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/storage_buckets.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/app.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/server.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/web.conf
  tests/testdata/test_addons/package_global_config_configuration/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/package/bin/storage_buckets.py
  tests/testdata/test_addons/package_global_config_everything/package/default/restmap.conf
  tests/testdata/test_addons/package_global_config_everything/package/default/web.conf
  tests/ui/pages/account_page.py
  tests/ui/test_configuration_page_account_tab.py
  tests/unit/generators/conf_files/test_create_restmap_conf.py
  tests/unit/generators/conf_files/test_create_web_conf.py
  tests/unit/test_auto_gen_comparator.py
  tests/unit/testdata/valid_config_logging_with_user_defined_handlers.json
  ui/package.json
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/tests/BaseFormView.test.tsx
  ui/src/components/BaseFormView/tests/contextMocks.ts
  ui/src/components/EntityModal/TestConfig.ts
  ui/src/mocks/globalConfigMock.ts
  ui/src/types/globalConfig/pages.ts
  ui/yarn.lock
Labels: size/XXL

#1908 feat: add check for existence of python scripts in user-defined handler
  splunk_add_on_ucc_framework/global_config_validator.py
  tests/testdata/test_addons/package_global_config_configuration/package/bin/someFile.py
  tests/unit/test_check_globalConfig.py
  tests/unit/test_global_config_validator.py
  tests/unit/testdata/invalid_config_with_user_defined_rest_handlers.json
Labels: size/M

#1921 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XXL

#1857 feat(date): date picker as a new component
  docs/entity/components.md
  docs/images/components/datepicker_component.png
  splunk_add_on_ucc_framework/global_config_validator.py
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/inputs.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/example_input_two.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_example_input_two.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/inputs.conf
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  ui/src/components/DatePickerComponent/DatePickerComponent.test.tsx
  ui/src/components/DatePickerComponent/DatePickerComponent.tsx
  ui/src/components/DatePickerComponent/stories/DatePickerComponent.stories.tsx
  ui/src/components/DatePickerComponent/stories/__images__/DatePickerComponent-date-disabled-chromium.png
  ui/src/components/DatePickerComponent/stories/__images__/DatePickerComponent-date-selected-chromium.png
  ui/src/components/DatePickerComponent/stories/__images__/DatePickerComponent-date-selected-gb-chromium.png
  ui/src/components/DatePickerComponent/stories/__images__/DatePickerComponent-date-selectedzhcn-chromium.png
  ui/src/components/DatePickerComponent/stories/__images__/DatePickerComponent-default-chromium.png
  ui/src/constants/ControlTypeMap.ts
Labels: size/L

#1924 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/S
