Repository splunk/addonfactory-ucc-generator, pull requests merged in 2025-03, with the labels that each got.

#1600 refactor: improve installation error message
  splunk_add_on_ucc_framework/install_python_libraries.py
  tests/unit/test_install_python_libraries.py
Labels: size/M

#1606 fix(validation): correctly validate empty not required data
  ui/src/util/Validator.js
  ui/src/util/tests/validators.test.ts
Labels: size/S

#1601 docs: use Admonition instead of details in modifications description
  docs/entity/modifyFieldsOnValue.md
Labels: size/L

#1613 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/L

#1615 ci(ta-tests): run splunktaucclib from branch
  .github/workflows/ta-tests.yml
Labels: size/M

#1604 refactor: add types and move validator to ts
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/CheckboxGroup/checkboxGroup.utils.ts
  ui/src/components/CheckboxGroup/checkboxGroupValidation.ts
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/types/components/BaseFormTypes.ts
  ui/src/types/globalConfig/validators.ts
  ui/src/util/Validator.ts
  ui/src/util/tests/validators.test.ts
Labels: javascript, size/XL

#1624 ci(code-cov): add simple code cov comparator
  .github/scripts/code-coverage.mjs
  .github/workflows/code-cov.yml
Labels: size/L

#1621 ci(ta-tests): replace pip poetry installation with their script
  .github/workflows/ta-tests.yml
Labels: size/S

#1622 docs: change the PR template and the contibuting guide
  .github/PULL_REQUEST_TEMPLATE.md
  docs/contributing.md
Labels: size/M

#1630 feat: skip help links in inputs.conf.spec
  splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/inputs.conf.spec
  tests/unit/generators/conf_files/test_create_inputs_conf.py
Labels: size/S

#1632 revert: "feat: skip help links in inputs.conf.spec"
  splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/inputs.conf.spec
  tests/unit/generators/conf_files/test_create_inputs_conf.py
Labels: size/S

#1628 fix: more info correctly expands
  ui/package.json
  ui/src/components/SingleInputComponent/SingleInputComponent.tsx
  ui/src/components/table/tests/CustomTable.test.tsx
  ui/src/components/table/tests/TableExpansionRow.test.tsx
  ui/src/components/table/tests/mocks.ts
  ui/src/pages/Input/stories/InputPage.stories.tsx
  ui/yarn.lock
Labels: size/L

#1634 chore(button,menu): remove deprecated appearance and icon properties
  ui/src/components/CheckboxGroup/CheckboxGroup.tsx
  ui/src/components/CheckboxTree/CheckboxTree.tsx
  ui/src/components/MenuInput/MenuInput.tsx
  ui/src/components/table/CustomTableRow.tsx
Labels: size/S

#1637 ci(ta-tests): add retry logic poetry install
  .github/workflows/ta-tests.yml
Labels: size/M

#1635 feat(TextArea): remove clear button
  ui/src/components/TextAreaComponent/TextAreaComponent.tsx
Labels: size/XS

#1629 test(ui): add kvstore healthcheck and flaky decorator
  .github/workflows/build-test-release.yml
  tests/ui/conftest.py
  tests/ui/pytest.ini
  tests/ui/test_alert_actions_page.py
Labels: size/XS

#1620 fix: remove max length for checkboxgroup and checkboxtree label
  docs/entity/components.md
  splunk_add_on_ucc_framework/schema/schema.json
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-mixed-with-groups-chromium.png
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-with-single-group-chromium.png
  ui/src/components/Group/Group.tsx
Labels: size/S

#1647 revert: remove stretched out icons
  splunk_add_on_ucc_framework/commands/init.py
  splunk_add_on_ucc_framework/templates/Icons/appLogo.png
  splunk_add_on_ucc_framework/templates/Icons/appLogo_2x.png
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/static/appLogo.png
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/static/appLogo_2x.png
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/static/appLogo.png
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/static/appLogo_2x.png
  tests/testdata/test_addons/package_global_config_everything/package/static/appLogo.png
  tests/testdata/test_addons/package_global_config_everything/package/static/appLogo_2x.png
  tests/ui/conftest.py
Labels: size/XS

#1649 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XL

#1636 fix: checkboxgroup select all button selects disabled fields
  ui/src/components/CheckboxGroup/CheckboxGroup.test.tsx
  ui/src/components/CheckboxGroup/CheckboxGroup.tsx
Labels: size/M

#1633 chore(modals): add placeholder for return focus
  ui/src/components/AcceptModal/AcceptModal.test.tsx
  ui/src/components/AcceptModal/AcceptModal.tsx
  ui/src/components/AcceptModal/stories/AcceptModal.stories.ts
  ui/src/components/ConfigurationTable.jsx
  ui/src/components/DashboardInfoModal/DashboardInfoModal.tsx
  ui/src/components/DeleteModal/DeleteModal.test.tsx
  ui/src/components/DeleteModal/DeleteModal.tsx
  ui/src/components/DeleteModal/stories/DeleteModal.stories.tsx
  ui/src/components/EntityModal/EntityModal.test.tsx
  ui/src/components/EntityModal/EntityModal.tsx
  ui/src/components/EntityModal/stories/EntityModal.stories.tsx
  ui/src/components/ErrorModal/ErrorModal.tsx
  ui/src/components/ErrorModal/stories/ErrorModal.stories.tsx
  ui/src/components/FormModifications/FormModifications.test.tsx
  ui/src/components/InteractAllStatusButton.tsx
  ui/src/components/table/CustomTable.tsx
  ui/src/components/table/CustomTableRow.tsx
  ui/src/components/table/tests/CustomTableRowConfirmation.test.tsx
  ui/src/pages/Dashboard/DataIngestionModal.tsx
  ui/src/pages/Input/InputPage.tsx
  ui/src/util/configManager.tsx
Labels: size/L

#1662 feat: introduce GlobalConfig.from_app_manifest
  splunk_add_on_ucc_framework/global_config.py
  tests/unit/test_global_config.py
  tests/unit/test_global_config_validator.py
Labels: size/M

#1661 feat: introduce GlobalConfig.from_app_manifest
  .coveragerc
  splunk_add_on_ucc_framework/global_config.py
  splunk_add_on_ucc_framework/global_config_update.py
  tests/unit/test_global_config.py
  tests/unit/test_global_config_validator.py
Labels: size/L

#1669 feat: create globalConfig from app.manifest
  .coveragerc
  docs/generated_files.md
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/generators/doc_generator.py
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_no_global_config/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
  tests/testdata/expected_addons/expected_output_no_global_config/Splunk_TA_UCCExample/appserver/static/openapi.json
  tests/unit/generators/test_doc_generator.py
  tests/unit/test_install_python_libraries.py
Labels: size/L
