Repository splunk/addonfactory-ucc-generator, pull requests merged in 2025-02, with the labels that each got.

#1547 fix: do not require calls of _reload endpoint
  splunk_add_on_ucc_framework/commands/rest_builder/endpoint/base.py
  splunk_add_on_ucc_framework/commands/rest_builder/endpoint/multiple_model.py
  splunk_add_on_ucc_framework/commands/rest_builder/endpoint/single_model.py
  splunk_add_on_ucc_framework/commands/rest_builder/global_config_builder_schema.py
  splunk_add_on_ucc_framework/install_python_libraries.py
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_settings.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_settings.py
  tests/testdata/test_addons/package_files_conflict_test/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
  tests/testdata/test_addons/package_global_config_only_one_tab/globalConfig.json
  tests/unit/test_endpoint.py
  tests/unit/test_install_python_libraries.py
Labels: size/L

#1570 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XXL

#1571 ci(npm-publish): add id-token write access
  .github/workflows/npm-publish.yml
Labels: size/XS

#1550 refactor(Dashboard): remove any type and add Zod validation
  ui/src/pages/Dashboard/DashboardModal.tsx
  ui/src/pages/Dashboard/DataIngestion.tsx
  ui/src/pages/Dashboard/DataIngestion.types.ts
Labels: javascript, size/M

#1530 feat: add default values of entities to inputs.conf
  splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
  splunk_add_on_ucc_framework/templates/conf_files/inputs_conf.template
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/inputs.conf
  tests/unit/generators/conf_files/test_create_inputs_conf.py
Labels: enhancement, size/M

#1529 feat: add support for custom REST handlers without UI in openapi.json
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/commands/openapi_generator/oas.py
  splunk_add_on_ucc_framework/commands/openapi_generator/ucc_to_oas.py
  splunk_add_on_ucc_framework/commands/rest_builder/user_defined_rest_handlers.py
  splunk_add_on_ucc_framework/global_config.py
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/appserver/static/openapi.json
  tests/testdata/test_addons/package_global_config_configuration/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/unit/test_schema.py
  tests/unit/test_user_defined_rest_handlers.py
Labels: size/XXL

#1564 fix(hideForPlatform): hide inputs when in groups menu
  ui/src/components/MenuInput/MenuInput.test.tsx
  ui/src/components/MenuInput/MenuInput.tsx
  ui/src/components/MenuInput/stories/MenuInput.stories.tsx
  ui/src/components/MenuInput/stories/__images__/MenuInput-with-opened-menu-chromium.png
  ui/src/components/MenuInput/stories/__images__/MenuInput-with-opened-sub-menu-chromium.png
Labels: javascript, size/L

#1413 feat: allow same service name across different inputs
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/ui/test_input_page.py
  ui/src/components/BaseFormView/BaseFormConfigMock.ts
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
  ui/src/components/BaseFormView/tests/BaseFormView.test.tsx
  ui/src/components/BaseFormView/tests/BaseFormViewGrups.test.tsx
  ui/src/components/BaseFormView/tests/configMocks.ts
  ui/src/components/BaseFormView/tests/contextMocks.ts
  ui/src/components/table/CustomTable.tsx
  ui/src/context/TableContext.tsx
  ui/src/types/globalConfig/pages.ts
Labels: javascript, size/XXL

#1579 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  splunk_add_on_ucc_framework/global_config.py
  splunk_add_on_ucc_framework/schema/schema.json
  ui/package.json
Labels: size/M

#1576 fix: correctly display status in more info
  ui/src/components/table/TableExpansionRowData.jsx
  ui/src/components/table/tests/TableExpansionRowData.test.tsx
Labels: bug, javascript, size/M

#1561 feat(helplink): links as part of longer text, new lines
  docs/entity/components.md
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/splunk_ta_uccexample_account.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  ui/src/components/HelpLinkComponent/HelpLinkComponent.tsx
  ui/src/components/HelpLinkComponent/stories/HelpLinkComponent.stories.ts
  ui/src/components/HelpLinkComponent/stories/__images__/HelpLinkComponent-base-chromium.png
  ui/src/components/HelpLinkComponent/stories/__images__/HelpLinkComponent-help-as-text-with-links-chromium.png
  ui/src/components/HelpLinkComponent/stories/__images__/HelpLinkComponent-help-in-many-lines-chromium.png
  ui/src/components/HelpLinkComponent/stories/__images__/HelpLinkComponent-help-many-lines-and-link-chromium.png
  ui/src/components/HelpLinkComponent/stories/__images__/HelpLinkComponent-help-no-links-in-many-lines-chromium.png
  ui/src/components/HelpLinkComponent/stories/__images__/HelpLinkComponent-one-link-many-lines-chromium.png
  ui/src/components/HelpLinkComponent/tests/HelpLinkComponent.test.tsx
  ui/src/components/SubDescription/SubDescription.test.tsx
  ui/src/components/SubDescription/SubDescription.tsx
  ui/src/types/globalConfig/entities.ts
  ui/src/util/textutils/textUtils.test.tsx
  ui/src/util/textutils/textUtils.tsx
Labels: enhancement, javascript, size/XL

#1584 chore: increase ui jest coverage
  ui/jest.config.ts
Labels: size/XS

#1577 ci: use latest version of appinspect actions
  .github/workflows/build-test-release.yml
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/app.manifest
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/app.conf
Labels: dependencies, size/XS

#1562 feat(help): message with links and new lines
  docs/advanced/sub_description.md
  docs/entity/help_message.md
  docs/entity/index.md
  mkdocs.yml
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/ui/test_configuration_page_account_tab.py
  ui/src/components/ControlWrapper/ControlWrapper.tsx
  ui/src/components/ControlWrapper/stories/ControlWrapper.stories.ts
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-help-with-link-chromium.png
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-multi-line-help-text-chromium.png
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-multi-line-help-text-with-links-chromium.png
  ui/src/components/ControlWrapper/test/ControlWrapper.test.tsx
  ui/src/components/FormModifications/FormModifications.test.tsx
  ui/src/components/HelpLinkComponent/stories/__images__/HelpLinkComponent-help-in-many-lines-chromium.png
  ui/src/types/globalConfig/entities.ts
Labels: javascript, size/XL

#1583 ci(npm): allow to publish prerelease with manual workflow run
  .github/workflows/npm-publish.yml
Labels: size/S

#1586 docs: update on OS-dependent libraries
  docs/advanced/os-dependent_libraries.md
Labels: size/S

#1540 docs: custom REST handlers documentation
  docs/options/index.md
  docs/options/rest_handlers.md
  mkdocs.yml
Labels: size/L

#1588 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XL

#1585 refactor(ui): move out AppProviders and make EntryPage type safe
  ui/.storybook/withSplunkTheme.tsx
  ui/src/pages/AppProviders.tsx
  ui/src/pages/EntryPage.tsx
  ui/src/pages/GlobalStyles.ts
  ui/src/pages/entry_page.jsx
  ui/src/pages/style.css
  ui/src/types/modules.d.ts
  ui/webpack.config.js
Labels: size/L

#1589 ci(npm): fix release publish command
  .github/workflows/build-test-release.yml
  .github/workflows/npm-publish.yml
Labels: size/XS

#1572 feat(modals): provide support for custom headers
  docs/configurations/index.md
  docs/inputs/index.md
  splunk_add_on_ucc_framework/schema/schema.json
  ui/src/components/ConfigurationTable.jsx
  ui/src/components/DeleteModal/DeleteModal.test.tsx
  ui/src/components/DeleteModal/DeleteModal.tsx
  ui/src/components/table/CustomTable.tsx
  ui/src/components/table/stories/configMockups.ts
  ui/src/components/table/tests/TableWrapper.test.tsx
  ui/src/pages/Configuration/stories/ConfigurationPage.stories.tsx
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-configuration-custom-header-chromium.png
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-configuration-page-view-chromium.png
  ui/src/pages/Configuration/stories/globalConfig.json
  ui/src/pages/Input/InputPage.tsx
  ui/src/pages/Input/stories/InputPage.stories.tsx
  ui/src/pages/Input/stories/__images__/InputPage-input-page-expanded-row-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-add-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-update-input-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-tab-custom-header-chromium.png
  ui/src/pages/Input/stories/globalConfig.json
  ui/src/types/globalConfig/pages.ts
Labels: size/XL

#1591 ci: build TAs with current version of UCC
  .github/workflows/ta-tests.yml
Labels: size/L

#1563 test: more features in "everything" globalConfig file
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/inputs.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/example_input_three_helper.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/service_inside_menu_four.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/service_inside_menu_one.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/service_inside_menu_three.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/service_inside_menu_two.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_service_inside_menu_four.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_service_inside_menu_one.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_service_inside_menu_three.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_service_inside_menu_two.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/inputs.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/web.conf
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/ui/test_input_page.py
Labels: size/XL

#1596 docs: modifications troubleshooting
  docs/entity/modifyFieldsOnValue.md
Labels: size/M

#1602 fix(validation): correctly display error in save validator fnc
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/types/components/BaseFormTypes.ts
  ui/src/types/components/CustomHookClass.ts
  ui/src/types/components/shareableTypes.ts
  ui/src/util/Validator.js
  ui/src/util/tests/validators.test.ts
Labels: size/L

#1595 refactor: move config tabs method in GlobalConfig class
  splunk_add_on_ucc_framework/global_config.py
  splunk_add_on_ucc_framework/global_config_update.py
  splunk_add_on_ucc_framework/global_config_validator.py
  tests/unit/test_global_config.py
  tests/unit/test_global_config_update.py
Labels: size/M
