Repository splunk/addonfactory-ucc-generator, pull requests merged in 2025-05, with the labels that each got.

#1721 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XXL

#1702 feat: added ucc-gen validate command support
  docs/commands.md
  poetry.lock
  pyproject.toml
  splunk_add_on_ucc_framework/commands/validate.py
  splunk_add_on_ucc_framework/main.py
  tests/unit/commands/test_validate.py
Labels: enhancement, size/L

#1728 revert: remove ucc-gen validate command support
  docs/commands.md
  poetry.lock
  pyproject.toml
  splunk_add_on_ucc_framework/commands/validate.py
  splunk_add_on_ucc_framework/main.py
  tests/unit/commands/test_validate.py
Labels: size/L

#1719 docs: interval docs fix
  docs/entity/components.md
Labels: size/S

#1725 fix: reauthenticate when an account is edited
  splunk_add_on_ucc_framework/commands/rest_builder/endpoint/single_model.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/unit/test_endpoint.py
Labels: size/S

#1726 fix(oauth_client_credentials): reflects state correctly on edit/config
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/tests/BaseFormView.test.tsx
  ui/src/components/BaseFormView/tests/contextMocks.ts
Labels: size/L

#1727 fix: OAuth error messages
  splunk_add_on_ucc_framework/commands/rest_builder/endpoint/single_model.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/unit/test_endpoint.py
Labels: size/M

#1703 refactor: introduce vite as build tool
  splunk_add_on_ucc_framework/package/appserver/templates/base.html
  splunk_add_on_ucc_framework/package/appserver/templates/redirect.html
  ui/.eslintrc.cjs
  ui/.storybook/main.ts
  ui/.storybook/test-runner.ts
  ui/CONTRIBUTING.md
  ui/babel.config.cjs
  ui/package.json
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
  ui/src/components/CheckboxTree/StyledComponent.tsx
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/components/CustomTab/CustomTab.tsx
  ui/src/components/EntityPage/EntityPage.tsx
  ui/src/components/ErrorBoundary/ErrorBoundary.tsx
  ui/src/components/Group/Group.tsx
  ui/src/components/InteractAllStatusButton.tsx
  ui/src/components/MenuInput/MenuInput.tsx
  ui/src/components/SingleInputComponent/SingleInputComponent.tsx
  ui/src/components/SubDescription/SubDescription.tsx
  ui/src/components/table/CustomTableCell.tsx
  ui/src/components/table/CustomTableControl.tsx
  ui/src/components/table/CustomTableStyle.tsx
  ui/src/pages/AppProviders.tsx
  ui/src/pages/Dashboard/DashboardPage.tsx
  ui/src/pages/Dashboard/DataIngestionModal.tsx
  ui/src/pages/Dashboard/Error.tsx
  ui/src/pages/Dashboard/dashboardStyle.css
  ui/src/pages/Dashboard/dashboardStyle.ts
  ui/src/pages/Dashboard/utils.tsx
  ui/src/pages/EntryPage.tsx
  ui/src/pages/GlobalStyles.ts
  ui/src/pages/Input/InputPageStyle.tsx
  ui/src/pages/UccInit.tsx
  ui/src/pages/stories/GlobalConfigPlayground.stories.tsx
  ui/tsconfig.app.json
  ui/tsconfig.json
  ui/tsconfig.lib.json
  ui/tsconfig.node.json
  ui/vite.config.ts
  ui/vite.lib.config.ts
  ui/webpack.config.js
  ui/webpack.config.lib.js
  ui/yarn.lock
Labels: size/XXL

#1692 docs: documentation changes for custom search command
  docs/custom_search_commands.md
  docs/images/custom_search_command_output.png
  mkdocs.yml
Labels: documentation, size/L

#1695 feat: generation of `searchbnf.conf`
  docs/generated_files.md
  splunk_add_on_ucc_framework/generators/conf_files/__init__.py
  splunk_add_on_ucc_framework/generators/conf_files/create_searchbnf_conf.py
  splunk_add_on_ucc_framework/generators/file_const.py
  splunk_add_on_ucc_framework/templates/conf_files/searchbnf_conf.template
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/searchbnf.conf
  tests/unit/generators/conf_files/test_conf_files_init.py
  tests/unit/generators/conf_files/test_create_searchbnf_conf.py
  tests/unit/generators/test_doc_generator.py
  tests/unit/test_utils.py
Labels: enhancement, size/L

#1694 feat: generation of `commands.conf`
  docs/generated_files.md
  splunk_add_on_ucc_framework/generators/conf_files/__init__.py
  splunk_add_on_ucc_framework/generators/conf_files/create_commands_conf.py
  splunk_add_on_ucc_framework/generators/file_const.py
  splunk_add_on_ucc_framework/templates/conf_files/commands_conf.template
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/commands.conf
  tests/unit/generators/conf_files/test_conf_files_init.py
  tests/unit/generators/conf_files/test_create_commands_conf.py
  tests/unit/generators/test_doc_generator.py
  tests/unit/test_utils.py
Labels: enhancement, size/L

#1697 feat: generation of python files for custom search command
  docs/generated_files.md
  splunk_add_on_ucc_framework/generators/file_const.py
  splunk_add_on_ucc_framework/generators/python_files/__init__.py
  splunk_add_on_ucc_framework/generators/python_files/create_custom_command_python.py
  splunk_add_on_ucc_framework/templates/custom_command/dataset_processing.template
  splunk_add_on_ucc_framework/templates/custom_command/generating.template
  splunk_add_on_ucc_framework/templates/custom_command/streaming.template
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/countmatches.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/countmatchescommand.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/filter.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/filtercommand.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/generatetext.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/generatetextcommand.py
  tests/unit/generators/python_files/test_create_custom_command_python.py
  tests/unit/generators/python_files/test_python_files_init.py
  tests/unit/generators/test_doc_generator.py
  tests/unit/generators/test_init_.py
  tests/unit/test_utils.py
Labels: enhancement, size/L

#1736 refactor: refactored inconsistent code
  splunk_add_on_ucc_framework/generators/conf_files/create_account_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_alert_actions_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_eventtypes_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_restmap_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_server_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_settings_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_tags_conf.py
  splunk_add_on_ucc_framework/generators/html_files/create_alert_actions_html.py
  splunk_add_on_ucc_framework/generators/xml_files/create_configuration_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_dashboard_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_default_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_inputs_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_redirect_xml.py
  tests/unit/generators/conf_files/test_create_account_conf_spec.py
  tests/unit/generators/conf_files/test_create_alert_actions_conf.py
  tests/unit/generators/conf_files/test_create_eventypes_conf.py
  tests/unit/generators/conf_files/test_create_restmap_conf.py
  tests/unit/generators/conf_files/test_create_server_conf.py
  tests/unit/generators/conf_files/test_create_tags_conf.py
  tests/unit/generators/html_files/test_create_alert_actions_html.py
  tests/unit/generators/xml_files/test_create_configuration_xml.py
  tests/unit/generators/xml_files/test_create_dashboard_xml.py
  tests/unit/generators/xml_files/test_create_inputs_xml.py
  tests/unit/generators/xml_files/test_create_redirect_xml.py
Labels: refactor, size/M

#1693 feat: base code for supporting custom search command
  docs/generated_files.md
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/const.py
  splunk_add_on_ucc_framework/generators/conf_files/__init__.py
  splunk_add_on_ucc_framework/generators/conf_files/create_commands_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_searchbnf_conf.py
  splunk_add_on_ucc_framework/generators/file_const.py
  splunk_add_on_ucc_framework/generators/python_files/__init__.py
  splunk_add_on_ucc_framework/generators/python_files/create_custom_command_python.py
  splunk_add_on_ucc_framework/global_config.py
  splunk_add_on_ucc_framework/global_config_validator.py
  splunk_add_on_ucc_framework/schema/schema.json
  splunk_add_on_ucc_framework/templates/conf_files/commands_conf.template
  splunk_add_on_ucc_framework/templates/conf_files/searchbnf_conf.template
  splunk_add_on_ucc_framework/templates/custom_command/dataset_processing.template
  splunk_add_on_ucc_framework/templates/custom_command/generating.template
  splunk_add_on_ucc_framework/templates/custom_command/streaming.template
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/countmatches.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/countmatchescommand.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/filter.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/filtercommand.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/generatetext.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/generatetextcommand.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/commands.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/searchbnf.conf
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/package/bin/countmatches.py
  tests/testdata/test_addons/package_global_config_everything/package/bin/filter.py
  tests/testdata/test_addons/package_global_config_everything/package/bin/generatetext.py
  tests/unit/generators/conf_files/test_conf_files_init.py
  tests/unit/generators/conf_files/test_create_commands_conf.py
  tests/unit/generators/conf_files/test_create_searchbnf_conf.py
  tests/unit/generators/python_files/test_create_custom_command_python.py
  tests/unit/generators/python_files/test_python_files_init.py
  tests/unit/generators/test_doc_generator.py
  tests/unit/generators/test_init_.py
  tests/unit/test_const.py
  tests/unit/test_global_config.py
  tests/unit/test_global_config_validator.py
  tests/unit/test_utils.py
  tests/unit/testdata/invalid_config_for_custom_search_command.json
  tests/unit/testdata/valid_config.json
Labels: enhancement, size/XXL

#1706 feat: custom react component via context
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
  ui/src/components/BaseFormView/tests/BaseFormView.test.tsx
  ui/src/components/BaseFormView/tests/CustomHookMockForTest.ts
  ui/src/components/BaseFormView/tests/CustomHookMockForTestError.ts
  ui/src/components/BaseFormView/tests/configMocks.ts
  ui/src/components/ConfigurationFormView.jsx
  ui/src/components/CustomControl/CustomControl.test.tsx
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/components/CustomControl/mockCustomControlMockForTest.ts
  ui/src/components/CustomMenu/CustomMenu.tsx
  ui/src/components/CustomMenu/test/CustomMenu.test.tsx
  ui/src/components/CustomMenu/test/mocks/CustomMenuMock.ts
  ui/src/components/CustomTab/CustomTab.tsx
  ui/src/components/CustomTab/tests/configMocks.ts
  ui/src/components/CustomTab/tests/customTab.test.tsx
  ui/src/components/CustomTab/tests/mockCustomTabFile.ts
  ui/src/components/EntityModal/EntityModal.tsx
  ui/src/components/EntityPage/EntityPage.tsx
  ui/src/components/MenuInput/MenuInput.test.tsx
  ui/src/components/MenuInput/MenuInput.tsx
  ui/src/components/table/CustomTable.tsx
  ui/src/components/table/CustomTableCell.tsx
  ui/src/components/table/CustomTableControl.tsx
  ui/src/components/table/CustomTableRow.tsx
  ui/src/components/table/TableExpansionRow.jsx
  ui/src/components/table/tests/CustomTable.test.tsx
  ui/src/components/table/tests/CustomTableCell.test.tsx
  ui/src/components/table/tests/TableExpansionRow.test.tsx
  ui/src/components/table/tests/mocks/CustomCellMock.ts
  ui/src/components/table/tests/mocks/CustomInputRowMock.tsx
  ui/src/context/CustomComponentContext.tsx
  ui/src/pages/EntryPage.tsx
  ui/src/pages/UccInit.tsx
  ui/src/publicApi.ts
  ui/src/types/CustomTypes.ts
  ui/src/types/components/CustomHookClass.ts
  ui/vite.config.ts
Labels: size/XXL

#1749 refactor: update oauth type labels
  tests/ui/test_configuration_page_account_tab.py
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/tests/BaseFormView.test.tsx
  ui/src/components/EntityModal/EntityModal.test.tsx
Labels: size/S

#1752 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XXL

#1744 refactor: UserDefinedRestHandlers takes all definitions directly
  .flake8
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/commands/rest_builder/user_defined_rest_handlers.py
  splunk_add_on_ucc_framework/global_config.py
  tests/unit/conftest.py
  tests/unit/generators/conf_files/test_create_restmap_conf.py
  tests/unit/generators/conf_files/test_create_web_conf.py
  tests/unit/test_user_defined_rest_handlers.py
  tests/unit/testdata/valid_config_logging_with_user_defined_handlers.json
Labels: size/L

#1754 test: modifications due to dashboard package update
  .github/workflows/storybook-visual.yml
  ui/jest.polyfills.ts
  ui/package.json
  ui/src/pages/Dashboard/tests/DashBoardPage.test.tsx
  ui/src/pages/Dashboard/tests/DashboardModal.test.tsx
  ui/src/pages/Dashboard/tests/mockMatchMediaForDashboardPage.ts
  ui/yarn.lock
Labels: size/XL

#1731 feat(playground): api calls as success to enable internal data flow
  ui/src/pages/stories/GlobalConfigPlayground.stories.tsx
Labels: size/S

#1755 fix: set host and port for proxy as required
  docs/configurations/proxy.md
  splunk_add_on_ucc_framework/tabs/proxy_tab.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_settings.py
  tests/ui/test_configuration_page_proxy_tab.py
  tests/unit/tabs/test_proxy_tab.py
Labels: size/M

#1718 fix: custom tab without entity error
  docs/custom_ui_extensions/standard/custom_tab.md
  docs/images/custom_ui_extensions/Custom_Tab_Output.png
  splunk_add_on_ucc_framework/commands/openapi_generator/ucc_to_oas.py
  splunk_add_on_ucc_framework/commands/rest_builder/global_config_builder_schema.py
  splunk_add_on_ucc_framework/generators/conf_files/create_settings_conf.py
  splunk_add_on_ucc_framework/global_config_validator.py
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/splunk_ta_uccexample_settings.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/custom/custom_tab.js
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/splunk_ta_uccexample_settings.conf
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/package/appserver/static/js/build/custom/custom_tab.js
  tests/unit/commands/openapi_generator/test_ucc_to_oas.py
  tests/unit/conftest.py
  tests/unit/testdata/openapi.json.custom_tab_without_entity.generated
  tests/unit/testdata/valid_config_custom_tab_without_entity.json
Labels: size/L

#1757 fix: remove support for interval and index type of entities for alerts
  splunk_add_on_ucc_framework/global_config.py
  splunk_add_on_ucc_framework/global_config_update.py
  tests/smoke/test_ucc_build.py
  tests/unit/test_global_config.py
  tests/unit/test_global_config_update.py
  tests/unit/testdata/valid_config_expand.json
  tests/unit/testdata/valid_config_only_interval_migration.json
Labels: bug, size/L
