Repository splunk/addonfactory-ucc-generator, pull requests merged in 2025-01, with the labels that each got.

#1510 feat: add option to disable inputs on creation
  docs/inputs/index.md
  splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
  splunk_add_on_ucc_framework/schema/schema.json
  splunk_add_on_ucc_framework/templates/conf_files/inputs_conf.template
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/inputs.conf
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/unit/generators/conf_files/test_create_inputs_conf.py
  tests/unit/testdata/valid_config.json
  ui/src/types/globalConfig/pages.ts
Labels: enhancement, size/L

#1519 feat: do not add _uccVersion to the root globalConfig file
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/global_config.py
  splunk_add_on_ucc_framework/schema/schema.json
  tests/smoke/test_ucc_build.py
  tests/testdata/test_addons/package_files_conflict_test/globalConfig.json
  tests/testdata/test_addons/package_global_config_configuration/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
  tests/testdata/test_addons/package_global_config_only_one_tab/globalConfig.json
  tests/unit/test_global_config.py
Labels: size/M

#1517 feat: support for Python 3.13
  .github/workflows/build-test-release.yml
  poetry.lock
  pyproject.toml
Labels: size/XS

#1509 feat(schema): schema changes for custom REST endpoints
  splunk_add_on_ucc_framework/schema/schema.json
  tests/unit/test_schema.py
Labels: size/L

#1501 ci: new add-on passes AppInspect
  .github/workflows/build-test-release.yml
  .gitignore
Labels: size/L

#1444 feat: proxy component
  .gitignore
  docs/configurations/index.md
  docs/configurations/proxy.md
  docs/images/configuration/proxy_tab.png
  docs/images/configuration/proxy_tab_custom.png
  docs/images/configuration/proxy_tab_with_warning.png
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/commands/init.py
  splunk_add_on_ucc_framework/global_config_update.py
  splunk_add_on_ucc_framework/install_python_libraries.py
  splunk_add_on_ucc_framework/main.py
  splunk_add_on_ucc_framework/schema/schema.json
  splunk_add_on_ucc_framework/tabs/__init__.py
  splunk_add_on_ucc_framework/tabs/proxy_tab.py
  splunk_add_on_ucc_framework/templates/globalConfig.json.init-template
  splunk_add_on_ucc_framework/templates/oauth.template
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_oauth.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_oauth.py
  tests/testdata/test_addons/package_global_config_configuration/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
  tests/ui/test_configuration_page_proxy_tab.py
  tests/unit/commands/test_init.py
  tests/unit/tabs/test_proxy_tab.py
  tests/unit/test_install_python_libraries.py
  tests/unit/test_main.py
  tests/unit/testdata/valid_config.json
  tests/unit/testdata/valid_config.yaml
  tests/unit/testdata/valid_config_logging_tab_not_migrated.json
  tests/unit/testdata/valid_config_multiple_account.json
  tests/unit/testdata/valid_config_only_configuration.json
  tests/unit/testdata/valid_single_authentication_config.json
  ui/src/pages/Configuration/stories/globalConfig.json
  ui/src/pages/stories/globalConfig/globalConfig.json
Labels: enhancement, size/XXL

#1523 chore(renovate): disable major updates for react-router-dom
  renovate.json
Labels: size/XS

#1522 style: update eslint-config and fix issues
  ui/.eslintrc.js
  ui/package.json
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/CheckboxGroup/mocks/checkboxGroupMocks.json
  ui/src/components/CheckboxGroup/mocks/checkboxGroupMocks.ts
  ui/src/components/CheckboxGroup/mocks/checkboxGroupRequiredMocks.json
  ui/src/components/CheckboxGroup/stories/CheckboxGroupInputPage.stories.tsx
  ui/src/components/SubDescription/SubDescription.tsx
  ui/src/context/PageContext.tsx
  ui/src/context/TableContext.tsx
  ui/src/pages/Dashboard/DataIngestion.tsx
  ui/yarn.lock
Labels: size/L

#1525 ci: update matrix action to v3.0
  .addonmatrix
  .github/workflows/build-test-release.yml
Labels: size/XS

#1527 ci: rollback splunk-appinspect to 3.8.1
  .github/workflows/build-test-release.yml
Labels: size/XS

#1511 chore: preparation to NPM publish
  .github/workflows/build-ui.yml
  ui/package.json
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/CheckBoxComponent/CheckBoxComponent.tsx
  ui/src/components/ControlWrapper/stories/ControlWrapper.stories.ts
  ui/src/components/ControlWrapper/test/ControlWrapper.test.tsx
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/components/CustomControl/CustomControl.types.ts
  ui/src/components/CustomControl/CustomControlBase.ts
  ui/src/components/CustomTab/CustomTab.tsx
  ui/src/components/CustomTab/CustomTab.types.ts
  ui/src/components/CustomTab/CustomTabBase.ts
  ui/src/components/DeleteModal/DeleteModal.tsx
  ui/src/components/EntityPage/EntityPage.tsx
  ui/src/components/TextAreaComponent/TextAreaComponent.tsx
  ui/src/components/TextComponent/TextComponent.tsx
  ui/src/publicApi.ts
  ui/src/types/components/BaseFormTypes.ts
  ui/src/types/components/CustomHookClass.ts
  ui/tsconfig.lib.json
Labels: size/L

#1533 chore(storybook): migrate deprecated toolbar
  ui/.storybook/main.ts
  ui/.storybook/preview.tsx
Labels: size/L

#1536 revert: "ci: rollback splunk-appinspect to 3.8.1"
  .github/workflows/build-test-release.yml
Labels: size/XS

#1495 feat: add CheckboxTree component
  docs/entity/components.md
  docs/images/components/checkbox_tree_mixed_example.png
  splunk_add_on_ucc_framework/global_config_validator.py
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/inputs.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_three_custom.py
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/package/bin/splunk_ta_uccexample_rh_three_custom.py
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
  tests/unit/test_global_config_validator.py
  tests/unit/testdata/invalid_config_checkbox_tree_duplicate_field_in_options_groups.json
  tests/unit/testdata/invalid_config_checkbox_tree_duplicate_field_in_options_rows.json
  tests/unit/testdata/invalid_config_checkbox_tree_undefined_field_used_in_groups.json
  ui/src/components/CheckboxGroup/checkboxGroup.utils.ts
  ui/src/components/CheckboxTree/CheckboxSubTree.tsx
  ui/src/components/CheckboxTree/CheckboxTree.test.tsx
  ui/src/components/CheckboxTree/CheckboxTree.tsx
  ui/src/components/CheckboxTree/CheckboxTree.utils.test.ts
  ui/src/components/CheckboxTree/CheckboxTree.utils.ts
  ui/src/components/CheckboxTree/CheckboxTreeRow.tsx
  ui/src/components/CheckboxTree/CheckboxTreeRowWrapper.tsx
  ui/src/components/CheckboxTree/StyledComponent.tsx
  ui/src/components/CheckboxTree/mocks/CheckboxTreeMocks.json
  ui/src/components/CheckboxTree/mocks/CheckboxTreeMocks.ts
  ui/src/components/CheckboxTree/mocks/CheckboxTreeRequiredMocks.json
  ui/src/components/CheckboxTree/stories/CheckboxTree.stories.tsx
  ui/src/components/CheckboxTree/stories/CheckboxTreeInputPage.stories.tsx
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-base-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-create-mode-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-input-page-view-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-mixed-with-groups-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-multiline-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-multiline-with-groups-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-required-view-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-with-single-group-chromium.png
  ui/src/components/CheckboxTree/types.ts
  ui/src/components/CheckboxTree/utils.test.tsx
  ui/src/components/CheckboxTree/utils.ts
  ui/src/constants/ControlTypeMap.ts
  ui/src/types/globalConfig/entities.ts
Labels: size/XXL

#1535 fix: prevent unnecessary updates to the globalConfig file
  splunk_add_on_ucc_framework/global_config_update.py
  tests/testdata/test_addons/package_files_conflict_test/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
  tests/testdata/test_addons/package_global_config_only_one_tab/globalConfig.json
  tests/unit/test_global_config_update.py
Labels: size/M

#1537 ci: npm publish dry run
  .github/workflows/build-test-release.yml
  .releaserc
Labels: size/L

#1541 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XL

#1545 test: ignore RUM availability errors
  tests/ui/conftest.py
Labels: size/XS

#1552 test: prevent warnings about unhandled side effects
  ui/src/components/CustomControl/CustomControl.test.tsx
  ui/src/components/EntityModal/EntityModal.test.tsx
  ui/src/components/InteractAllStatusButton.test.tsx
  ui/src/components/table/tests/CustomTableRow.test.tsx
  ui/src/components/table/tests/TableExpansionRow.test.tsx
Labels: javascript, size/L

#1554 chore(storybook): waitForPageReady for CI
  ui/.storybook/preview-head.html
  ui/.storybook/test-runner.ts
Labels: javascript, size/M

#1553 refactor(DeleteModal): class component into the functional one
  ui/src/components/DeleteModal/DeleteModal.tsx
Labels: javascript, size/L

#1549 chore(deps): add missing types deps for react and lodash
  renovate.json
  ui/package.json
  ui/yarn.lock
Labels: javascript, size/S

#1556 ci(npm): add registry-url
  .github/actions/cached-ui-deps/action.yml
Labels: size/XS

#1558 ci(test): ignore errors caused by RUM scripts
  tests/ui/conftest.py
Labels: size/XS

#1542 fix(a11y): connect labels to inputs
  ui/.storybook/withControlGroup.tsx
  ui/src/components/BaseFormView/BaseFormViewGrups.test.tsx
  ui/src/components/BaseFormView/tests/BaseFormView.test.tsx
  ui/src/components/CheckBoxComponent/CheckBoxComponent.tsx
  ui/src/components/CheckBoxComponent/stories/CheckBoxComponent.stories.tsx
  ui/src/components/CheckBoxComponent/stories/__images__/CheckBoxComponent-base-chromium.png
  ui/src/components/CheckboxGroup/CheckboxGroup.tsx
  ui/src/components/CheckboxGroup/CheckboxRow.tsx
  ui/src/components/CheckboxGroup/StyledComponent.tsx
  ui/src/components/CheckboxGroup/stories/CheckboxGroup.stories.tsx
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-base-chromium.png
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-create-mode-chromium.png
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-mixed-with-groups-chromium.png
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-multiline-chromium.png
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-with-single-group-chromium.png
  ui/src/components/CheckboxTree/CheckboxTree.tsx
  ui/src/components/CheckboxTree/StyledComponent.tsx
  ui/src/components/CheckboxTree/stories/CheckboxTree.stories.tsx
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-base-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-create-mode-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-mixed-with-groups-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-multiline-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-multiline-with-groups-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-with-single-group-chromium.png
  ui/src/components/ControlWrapper/ControlWrapper.tsx
  ui/src/components/ControlWrapper/utils.ts
  ui/src/components/FileInputComponent/FileInputComponent.tsx
  ui/src/components/FileInputComponent/stories/FileInputComponent.stories.tsx
  ui/src/components/FileInputComponent/stories/__images__/FileInputComponent-base-chromium.png
  ui/src/components/FileInputComponent/stories/__images__/FileInputComponent-encrypted-with-default-name-chromium.png
  ui/src/components/FileInputComponent/stories/__images__/FileInputComponent-with-default-name-chromium.png
  ui/src/components/FormModifications/FormModifications.test.tsx
  ui/src/components/MultiInputComponent/MultiInputComponent.test.tsx
  ui/src/components/MultiInputComponent/MultiInputComponent.tsx
  ui/src/components/MultiInputComponent/stories/MultiInputComponent.stories.tsx
  ui/src/components/MultiInputComponent/stories/__images__/MultiInputComponent-all-props-chromium.png
  ui/src/components/MultiInputComponent/stories/__images__/MultiInputComponent-base-chromium.png
  ui/src/components/MultiInputComponent/stories/__images__/MultiInputComponent-endpoint-api-chromium.png
  ui/src/components/RadioComponent/RadioComponent.tsx
  ui/src/components/RadioComponent/stories/RadioComponent.stories.ts
  ui/src/components/RadioComponent/stories/__images__/RadioComponent-base-chromium.png
  ui/src/components/SingleInputComponent/SingleInputComponent.test.tsx
  ui/src/components/SingleInputComponent/SingleInputComponent.tsx
  ui/src/components/SingleInputComponent/stories/SingleInputComponent.stories.tsx
  ui/src/components/SingleInputComponent/stories/__images__/SingleInputComponent-accept-any-input-chromium.png
  ui/src/components/SingleInputComponent/stories/__images__/SingleInputComponent-allow-deny-list-from-backend-chromium.png
  ui/src/components/SingleInputComponent/stories/__images__/SingleInputComponent-select-list-chromium.png
  ui/src/components/TextAreaComponent/TextAreaComponent.tsx
  ui/src/components/TextAreaComponent/stories/TextAreaComponent.stories.tsx
  ui/src/components/TextAreaComponent/stories/__images__/TextAreaComponent-base-chromium.png
  ui/src/components/TextComponent/TextComponent.tsx
  ui/src/components/TextComponent/stories/TextComponent.stories.tsx
  ui/src/components/TextComponent/stories/__images__/TextComponent-all-props-true-chromium.png
  ui/src/components/TextComponent/stories/__images__/TextComponent-base-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-add-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-update-input-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-tab-view-add-chromium.png
Labels: javascript, size/XL

#1544 ci: test-ui does not wait for test-smoke
  .github/workflows/build-test-release.yml
Labels: size/XS

#1551 refactor(storybook): fix types in stories
  ui/src/components/CheckboxGroup/stories/CheckboxGroupInputPage.stories.tsx
  ui/src/components/CheckboxTree/stories/CheckboxTreeInputPage.stories.tsx
  ui/src/components/table/stories/TableWrapper.stories.tsx
  ui/src/pages/stories/GlobalConfigPlayground.stories.tsx
Labels: javascript, size/M
