Repository splunk/addonfactory-ucc-generator, pull requests merged in 2025-08, with the labels that each got.

#1858 feat: upgrade ucc ui component to sui latest version
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/BaseFormViewUtils.ts
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-both-oauth-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-field-modify-itself-after-mods-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-field-modify-itself-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-oauth-basic-with-additional-field-types-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-oauth-oauth-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-ouath-basic-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-ouath-basic-cloud-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-ouath-basic-enterprise-chromium.png
  ui/src/components/ControlWrapper/ControlWrapper.tsx
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-base-chromium.png
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-help-with-link-chromium.png
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-multi-line-help-text-chromium.png
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-multi-line-help-text-with-links-chromium.png
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-with-modifications-chromium.png
  ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-with-modifications-make-required-chromium.png
  ui/src/components/EntityModal/stories/__images__/EntityModal-base-chromium.png
  ui/src/components/EntityModal/stories/__images__/EntityModal-inputs-chromium.png
  ui/src/components/EntityPage/stories/EntityPage.stories.tsx
  ui/src/components/EntityPage/stories/__images__/EntityPage-base-chromium.png
  ui/src/components/EntityPage/stories/__images__/EntityPage-inputs-chromium.png
  ui/src/components/ErrorBoundary/ErrorBoundary.style.ts
  ui/src/components/ErrorBoundary/ErrorBoundary.tsx
  ui/src/components/ErrorBoundary/stories/__images__/ErrorBoundary-base-chromium.png
  ui/src/components/table/CustomTableRow.tsx
  ui/src/components/table/TableExpansionRowData.jsx
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-configuration-custom-header-chromium.png
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-configuration-view-add-chromium.png
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-long-tab-name-story-chromium.png
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-multi-tabs-story-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-expanded-row-chromium.png
  ui/src/pages/stories/GlobalConfigPlayground.stories.tsx
  ui/src/pages/stories/__images__/GlobalConfigPlayground-global-config-playground-chromium.png
Labels: size/L

#1863 chore: align ui and backend schema
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
  tests/unit/testdata/invalid_custom_oauth_entities_not_defined.json
  tests/unit/testdata/invalid_oauth_config_with_labels_entities_not_defined.json
  tests/unit/testdata/valid_config_multiple_account.json
  tests/unit/testdata/valid_oauth_authentication_config_with_custom_oauth_and_labels.json
  tests/unit/testdata/valid_single_authentication_config.json
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/types/globalConfig/alerts.ts
  ui/src/types/globalConfig/entities.ts
  ui/src/types/globalConfig/meta.ts
Labels: size/M

#1882 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XXL

#1867 BREAKING CHANGE: remove support for --ui-source-map
  docs/commands.md
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/main.py
  splunk_add_on_ucc_framework/utils.py
  tests/smoke/test_ucc_build.py
  tests/unit/commands/test_build.py
  tests/unit/test_main.py
  ui/vite.config.ts
Labels: size/M

#1891 chore: fix python linter after oauth entity removal
  splunk_add_on_ucc_framework/global_config_update.py
Labels: size/XS

#1885 fix: test cases for sui-5
  ui/package-lock.json
  ui/package.json
  ui/src/components/CheckBoxComponent/CheckBoxComponent.test.tsx
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/components/InteractAllStatusButton.tsx
  ui/src/components/SingleInputComponent/SingleInputComponent.tsx
  ui/src/components/UCCButton/UCCButton.tsx
  ui/src/components/table/CustomTableStyle.tsx
  ui/src/components/table/TableExpansionRowData.jsx
  ui/src/components/table/stories/__images__/TableWrapper-simple-table-many-services-chromium.png
  ui/src/components/table/stories/__images__/TableWrapper-simple-table-style-page-chromium.png
  ui/src/components/table/table.utils.ts
  ui/src/components/table/tests/TableWrapper.test.tsx
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-configuration-page-view-chromium.png
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-long-tab-name-story-chromium.png
  ui/src/pages/Configuration/stories/__images__/ConfigurationPage-multi-tabs-story-chromium.png
  ui/src/pages/Configuration/tests/ConfigContext.test.tsx
  ui/src/pages/Dashboard/stories/DashboardPage.stories.tsx
  ui/src/pages/Dashboard/stories/__images__/DashboardPage-dashboard-page-view-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-expanded-row-chromium.png
  ui/src/tests/expectExtenders.ts
  ui/src/types/modules.d.ts
  ui/test.setup.ts
  ui/yarn.lock
Labels: size/XXL

#1874 BREAKING CHANGE: remove require js (amd) approach for custom elements
  docs/custom_ui_extensions/context/custom_hook_context.md
  docs/custom_ui_extensions/standard/custom_hook.md
  docs/custom_ui_extensions/standard/overview.md
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/splunk_ta_uccexample_account.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/custom/amdCustomHook.js
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/custom/amdCustomInputCell.js
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/custom/amdCustom_control.js
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/custom/amdCustom_input_row_replace.js
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_custom_amd_row_tab.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/app.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/server.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/web.conf
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/package/appserver/static/js/build/custom/amdCustomHook.js
  tests/testdata/test_addons/package_global_config_everything/package/appserver/static/js/build/custom/amdCustomInputCell.js
  tests/testdata/test_addons/package_global_config_everything/package/appserver/static/js/build/custom/amdCustom_control.js
  tests/testdata/test_addons/package_global_config_everything/package/appserver/static/js/build/custom/amdCustom_input_row_replace.js
  tests/testdata/test_addons/package_global_config_everything/package/default/restmap.conf
  tests/testdata/test_addons/package_global_config_everything/package/default/web.conf
  tests/ui/test_configuration_page_account_tab.py
  tests/unit/testdata/invalid_config_both_rest_handler_name_class_are_present.json
  tests/unit/testdata/invalid_config_both_rest_handler_name_module_are_present.json
  tests/unit/testdata/invalid_config_inputs_autoCompleteFields_duplicates.json
  tests/unit/testdata/invalid_config_inputs_multilevel_menu_duplicate_groups.json
  tests/unit/testdata/invalid_config_inputs_multilevel_menu_invalid_groupname_or_grouptitle.json
  tests/unit/testdata/invalid_config_inputs_multilevel_menu_invalid_groupservices.json
  tests/unit/testdata/invalid_config_inputs_services_duplicates.json
  tests/unit/testdata/invalid_config_no_configuration_tabs.json
  tests/unit/testdata/invalid_config_no_configuration_tabs.yaml
  tests/unit/testdata/invalid_config_only_rest_handler_class_is_present.json
  tests/unit/testdata/invalid_config_only_rest_handler_module_is_present.json
  tests/unit/testdata/invalid_config_with_oauth_fields.json
  tests/unit/testdata/valid_config.json
  tests/unit/testdata/valid_config.yaml
  tests/unit/testdata/valid_config_expand.json
  tests/unit/testdata/valid_config_logging_tab_not_migrated.json
  tests/unit/testdata/valid_config_only_interval_migration.json
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/components/CustomTab/CustomTab.tsx
  ui/src/components/MenuInput/MenuInput.test.tsx
  ui/src/components/MenuInput/stories/MenuInput.stories.tsx
  ui/src/components/table/CustomTableCell.tsx
  ui/src/components/table/CustomTableControl.tsx
  ui/src/components/table/TableWrapper.tsx
  ui/src/types/globalConfig/baseSchemas.ts
  ui/src/types/globalConfig/entities.ts
  ui/src/types/globalConfig/pages.ts
  ui/src/types/modules.d.ts
Labels: size/XL

#1880 feat: upgrade ucc ui component to sui latest version
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-config-page-groups-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-group-modifications-config-chromium.png
  ui/src/components/BaseFormView/stories/__images__/BaseFormView-input-page-groups-chromium.png
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-input-page-view-chromium.png
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-mixed-with-groups-chromium.png
  ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-required-view-chromium.png
  ui/src/components/CheckboxTree/CheckboxSubTree.tsx
  ui/src/components/CheckboxTree/StyledComponent.tsx
  ui/src/components/CheckboxTree/mocks/CheckboxTreeMocks.json
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-input-page-view-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-mixed-with-groups-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-multiline-with-groups-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-required-view-chromium.png
  ui/src/components/CheckboxTree/stories/__images__/CheckboxTree-with-single-group-chromium.png
  ui/src/components/EntityPage/EntityPage.tsx
  ui/src/components/EntityPage/stories/__images__/EntityPage-base-chromium.png
  ui/src/components/EntityPage/stories/__images__/EntityPage-inputs-chromium.png
  ui/src/components/Group/Group.tsx
  ui/src/components/Group/stories/__images__/Group-expandable-chromium.png
  ui/src/components/table/CustomTableStyle.tsx
  ui/src/components/table/stories/__images__/TableWrapper-simple-table-many-services-chromium.png
  ui/src/components/table/stories/__images__/TableWrapper-simple-table-style-page-chromium.png
  ui/src/pages/Dashboard/DataIngestionModal.tsx
  ui/src/pages/Dashboard/dashboardStyle.ts
  ui/src/pages/Dashboard/stories/__images__/DashboardPage-dashboard-page-view-chromium.png
  ui/src/pages/Input/stories/InputPage.stories.tsx
  ui/src/pages/Input/stories/__images__/InputPage-input-page-expanded-row-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-add-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-page-view-update-input-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-tab-custom-header-chromium.png
  ui/src/pages/Input/stories/__images__/InputPage-input-tab-view-add-chromium.png
Labels: size/L

#1884 fix: generation of web.conf for endpoints mentioned in endpointUrl
  docs/configurations/index.md
  docs/inputs/index.md
  docs/options/rest_handlers.md
  splunk_add_on_ucc_framework/commands/rest_builder/global_config_builder_schema.py
  splunk_add_on_ucc_framework/commands/rest_builder/user_defined_rest_handlers.py
  splunk_add_on_ucc_framework/generators/conf_files/create_restmap_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_web_conf.py
  splunk_add_on_ucc_framework/global_config.py
  splunk_add_on_ucc_framework/schema/schema.json
  splunk_add_on_ucc_framework/templates/conf_files/restmap_conf.template
  splunk_add_on_ucc_framework/templates/web_conf.template
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_addon_no_configuration/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/web.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/storage_buckets.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/web.conf
  tests/testdata/test_addons/package_global_config_configuration/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/package/bin/storage_buckets.py
  tests/testdata/test_addons/package_global_config_everything/package/default/restmap.conf
  tests/testdata/test_addons/package_global_config_everything/package/default/web.conf
  tests/unit/generators/conf_files/test_create_restmap_conf.py
  tests/unit/generators/conf_files/test_create_web_conf.py
  tests/unit/testdata/valid_config_logging_with_user_defined_handlers.json
  ui/src/types/globalConfig/pages.ts
Labels: enhancement, size/XL
