Repository splunk/addonfactory-ucc-generator, pull requests merged in 2025-04, with the labels that each got.

#1663 chore(deps): partial package updates plus security resolutions
  ui/package.json
  ui/src/pages/Dashboard/DashboardModal.tsx
  ui/src/pages/Dashboard/DataIngestion.types.ts
  ui/yarn.lock
Labels: size/XXL

#1671 refactor: globalConfig file is now required during the build process
  splunk_add_on_ucc_framework/generators/conf_files/create_account_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_app_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_eventtypes_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_restmap_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_server_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_settings_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_tags_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_web_conf.py
  splunk_add_on_ucc_framework/generators/file_generator.py
  splunk_add_on_ucc_framework/generators/html_files/create_alert_actions_html.py
  splunk_add_on_ucc_framework/generators/xml_files/create_configuration_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_dashboard_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_default_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_inputs_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_redirect_xml.py
  tests/unit/generators/conf_files/test_create_account_conf_spec.py
  tests/unit/generators/conf_files/test_create_alert_actions_conf.py
  tests/unit/generators/conf_files/test_create_app_conf.py
  tests/unit/generators/conf_files/test_create_inputs_conf.py
  tests/unit/generators/conf_files/test_create_restmap_conf.py
  tests/unit/generators/conf_files/test_create_settings_conf.py
  tests/unit/generators/conf_files/test_create_web_conf.py
  tests/unit/generators/html_files/test_create_alert_actions_html.py
  tests/unit/generators/test_file_generator.py
Labels: refactor, size/L

#1670 fix(import-from-aob): fixed incorrect merging and added app.manifest validations
  splunk_add_on_ucc_framework/commands/import_from_aob.py
  splunk_add_on_ucc_framework/commands/import_from_aob.sh
  tests/unit/commands/test_import_from_aob.py
  tests/unit/testdata/app.manifest_no_supported_deplyments
Labels: size/L

#1674 feat(build): --ui-source-map deprecation notice
  docs/commands.md
  splunk_add_on_ucc_framework/main.py
Labels: size/S

#1676 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XL

#1682 test: Add custom table tests
  ui/src/components/table/CustomTableControl.jsx
  ui/src/components/table/CustomTableRow.tsx
  ui/src/components/table/stories/TableWrapper.stories.tsx
  ui/src/components/table/stories/__images__/TableWrapper-ouath-basic-chromium.png
  ui/src/components/table/stories/__images__/TableWrapper-simple-config-with-status-mapped-chromium.png
  ui/src/components/table/stories/__images__/TableWrapper-simple-table-many-services-chromium.png
  ui/src/components/table/stories/__images__/TableWrapper-simple-table-style-page-chromium.png
  ui/src/components/table/stories/configMockups.ts
  ui/src/components/table/stories/rowDataMockup.ts
  ui/src/components/table/tests/CustomTableCell.test.tsx
  ui/src/components/table/tests/CustomTableRow.test.tsx
  ui/src/components/table/tests/TableExpansionRow.test.tsx
  ui/src/components/table/tests/TableHeader.test.tsx
  ui/src/components/table/tests/TableWrapper.test.tsx
  ui/src/components/table/tests/mocks.ts
  ui/src/components/table/tests/mocks/CustomCellMock.ts
  ui/src/components/table/tests/mocks/CustomCellMockError.ts
  ui/src/components/table/tests/mocks/CustomCellMockNoRender.ts
  ui/src/components/table/tests/mocks/CustomRowMock.ts
  ui/src/components/table/tests/mocks/CustomRowMockGetDLError.ts
  ui/src/components/table/tests/mocks/CustomRowMockGetDLUnvalid.ts
  ui/src/components/table/tests/mocks/CustomRowMockRenderError.ts
Labels: size/XXL

#1678 refactor: simplify doc_generator logic and testing
  .flake8
  splunk_add_on_ucc_framework/generators/doc_generator.py
  splunk_add_on_ucc_framework/generators/file_const.py
  tests/unit/generators/test_doc_generator.py
Labels: size/L

#1689 refactor: remove intermediate classes from generators
  splunk_add_on_ucc_framework/generators/conf_files/__init__.py
  splunk_add_on_ucc_framework/generators/conf_files/conf_generator.py
  splunk_add_on_ucc_framework/generators/conf_files/create_account_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_alert_actions_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_app_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_eventtypes_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_restmap_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_server_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_settings_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_tags_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_web_conf.py
  splunk_add_on_ucc_framework/generators/html_files/__init__.py
  splunk_add_on_ucc_framework/generators/html_files/create_alert_actions_html.py
  splunk_add_on_ucc_framework/generators/html_files/html_generator.py
  splunk_add_on_ucc_framework/generators/xml_files/__init__.py
  splunk_add_on_ucc_framework/generators/xml_files/create_configuration_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_dashboard_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_default_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_inputs_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_redirect_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/xml_generator.py
  tests/unit/generators/conf_files/test_conf_files_init.py
  tests/unit/generators/conf_files/test_conf_generator.py
  tests/unit/generators/conf_files/test_create_account_conf_spec.py
  tests/unit/generators/conf_files/test_create_alert_actions_conf.py
  tests/unit/generators/conf_files/test_create_app_conf.py
  tests/unit/generators/conf_files/test_create_eventypes_conf.py
  tests/unit/generators/conf_files/test_create_inputs_conf.py
  tests/unit/generators/conf_files/test_create_restmap_conf.py
  tests/unit/generators/conf_files/test_create_server_conf.py
  tests/unit/generators/conf_files/test_create_tags_conf.py
  tests/unit/generators/conf_files/test_create_web_conf.py
  tests/unit/generators/html_files/test_create_alert_actions_html.py
  tests/unit/generators/html_files/test_html_files_init.py
  tests/unit/generators/html_files/test_html_generator.py
  tests/unit/generators/xml_files/test_create_configuration_xml.py
  tests/unit/generators/xml_files/test_create_dashboard_xml.py
  tests/unit/generators/xml_files/test_create_default_xml.py
  tests/unit/generators/xml_files/test_create_inputs_xml.py
  tests/unit/generators/xml_files/test_create_redirect_xml.py
  tests/unit/generators/xml_files/test_xml_files_init.py
  tests/unit/generators/xml_files/test_xml_generator.py
Labels: refactor, size/XL

#1691 chore: remove unused files
  splunk_add_on_ucc_framework/commands/modular_alert_builder/alert_actions_exceptions.py
  splunk_add_on_ucc_framework/commands/modular_alert_builder/alert_actions_merge.py
Labels: size/M

#1677 refactor: custom menu to ts
  ui/src/components/CustomMenu/CustomMenu.tsx
  ui/src/components/CustomMenu/CustomMenuBase.ts
  ui/src/components/CustomMenu/test/CustomMenu.test.tsx
  ui/src/components/CustomMenu/test/mocks/CustomMenuMock.ts
  ui/src/components/CustomMenu/test/mocks/globalConfigMock.ts
  ui/src/components/MenuInput/MenuInput.tsx
  ui/src/publicApi.ts
Labels: size/L

#1685 feat: add delimiter for checkboxtree and checkboxgroup
  docs/entity/components.md
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  ui/src/components/CheckboxGroup/CheckboxGroup.test.tsx
  ui/src/components/CheckboxGroup/CheckboxGroup.tsx
  ui/src/components/CheckboxGroup/checkboxGroup.utils.test.ts
  ui/src/components/CheckboxGroup/checkboxGroup.utils.ts
  ui/src/components/CheckboxGroup/checkboxGroupValidation.ts
  ui/src/components/CheckboxTree/CheckboxTree.test.tsx
  ui/src/components/CheckboxTree/CheckboxTree.tsx
  ui/src/components/CheckboxTree/CheckboxTree.utils.ts
  ui/src/components/CheckboxTree/utils.test.tsx
  ui/src/components/CheckboxTree/utils.ts
  ui/src/types/globalConfig/entities.ts
Labels: size/L

#1683 refactor: custom table cell typescript
  ui/src/components/table/CustomTableCell.tsx
  ui/src/components/table/CustomTableCellBase.ts
  ui/src/components/table/CustomTableControl.jsx
  ui/src/components/table/CustomTableRow.tsx
  ui/src/components/table/tests/CustomTableCell.test.tsx
Labels: size/L

#1688 fix: show input type in inputs page
  ui/src/components/BaseFormView/tests/contextMocks.ts
  ui/src/components/table/TableWrapper.tsx
  ui/src/components/table/stories/__images__/TableWrapper-simple-table-many-services-chromium.png
  ui/src/components/table/stories/__images__/TableWrapper-simple-table-style-page-chromium.png
  ui/src/components/table/stories/configMockups.ts
  ui/src/components/table/tests/CustomTable.test.tsx
  ui/src/components/table/tests/TableWrapper.test.tsx
  ui/src/context/TableContext.tsx
Labels: size/L

#1684 refactor: custom-table-control-to-ts
  ui/src/components/table/CustomRowBase.ts
  ui/src/components/table/CustomTableControl.tsx
Labels: size/L

#1690 refactor: simplify WebConf class and testing of it
  splunk_add_on_ucc_framework/generators/conf_files/create_web_conf.py
  splunk_add_on_ucc_framework/generators/file_generator.py
  splunk_add_on_ucc_framework/templates/web_conf.template
  tests/unit/generators/conf_files/test_create_web_conf.py
  tests/unit/test_utils.py
Labels: size/L

#1608 feat: generate another .conf-file when conf parameter is used
  splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
  splunk_add_on_ucc_framework/templates/README/inputs_conf_spec.template
  splunk_add_on_ucc_framework/templates/conf_files/inputs_conf.template
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/inputs.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/some_conf.conf.spec
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/unit/generators/conf_files/test_create_inputs_conf.py
  tests/unit/testdata/openapi.json.valid_config.generated
  tests/unit/testdata/valid_config.json
Labels: size/L

#1699 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XL

#1700 chore: resolution http-proxy-middleware "^2.0.9"
  ui/package.json
  ui/yarn.lock
Labels: size/S

#1714 fix: fixed defaultView error
  splunk_add_on_ucc_framework/generators/xml_files/create_default_xml.py
  tests/unit/generators/xml_files/test_create_default_xml.py
Labels: size/M

#1708 feat: schema changes for OAuth 2.0 Client Credentials Grant
  splunk_add_on_ucc_framework/commands/rest_builder/global_config_builder_schema.py
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/splunk_ta_uccexample_account.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/ui/test_configuration_page_account_tab.py
  tests/unit/commands/rest_builder/test_global_config_builder_schema.py
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/EntityModal/EntityModal.test.tsx
  ui/src/components/EntityModal/TestConfig.ts
  ui/src/types/components/BaseFormTypes.ts
  ui/src/types/globalConfig/entities.ts
  ui/src/types/globalConfig/globalConfig.ts
  ui/src/util/api.ts
Labels: size/XL

#1707 feat: support for OAuth2 Client Credentials Grant in RH template
  splunk_add_on_ucc_framework/templates/oauth.template
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_oauth.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_oauth.py
  tests/unit/commands/rest_builder/test_oauth_model.py
Labels: size/L

#1710 fix: change sed backup extension
  splunk_add_on_ucc_framework/commands/import_from_aob.sh
Labels: size/S

#1709 feat: add links to something went wrong
  docs/troubleshooting.md
  ui/src/components/ErrorBoundary/ErrorBoundary.test.tsx
  ui/src/components/ErrorBoundary/ErrorBoundary.tsx
  ui/src/components/ErrorBoundary/stories/ErrorBoundary.stories.tsx
  ui/src/components/ErrorBoundary/stories/__images__/ErrorBoundary-base-chromium.png
  ui/src/pages/Dashboard/utils.tsx
  ui/src/util/searchUtil.test.ts
  ui/src/util/searchUtil.ts
Labels: size/L

#1716 docs: Oauth 2.0 client credentials info
  docs/advanced/oauth_support.md
Labels: size/M

#1717 chore: merge develop into main
  docs/advanced/oauth_support.md
  docs/troubleshooting.md
  splunk_add_on_ucc_framework/commands/import_from_aob.sh
  splunk_add_on_ucc_framework/commands/rest_builder/endpoint/single_model.py
  splunk_add_on_ucc_framework/commands/rest_builder/global_config_builder_schema.py
  splunk_add_on_ucc_framework/generators/xml_files/create_default_xml.py
  splunk_add_on_ucc_framework/schema/schema.json
  splunk_add_on_ucc_framework/templates/oauth.template
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_oauth.py
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/web.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/.appinspect.manualcheck.yaml
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/splunk_ta_uccexample_account.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_oauth.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/web.conf
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/ui/test_configuration_page_account_tab.py
  tests/unit/commands/rest_builder/test_global_config_builder_schema.py
  tests/unit/commands/rest_builder/test_oauth_model.py
  tests/unit/generators/conf_files/test_create_restmap_conf.py
  tests/unit/generators/conf_files/test_create_web_conf.py
  tests/unit/generators/xml_files/test_create_default_xml.py
  tests/unit/test_endpoint.py
  ui/jest.polyfills.ts
  ui/package.json
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/EntityModal/EntityModal.test.tsx
  ui/src/components/EntityModal/TestConfig.ts
  ui/src/components/ErrorBoundary/ErrorBoundary.test.tsx
  ui/src/components/ErrorBoundary/ErrorBoundary.tsx
  ui/src/components/ErrorBoundary/stories/ErrorBoundary.stories.tsx
  ui/src/components/ErrorBoundary/stories/__images__/ErrorBoundary-base-chromium.png
  ui/src/pages/Dashboard/tests/DashboardModal.test.tsx
  ui/src/pages/Dashboard/utils.tsx
  ui/src/types/components/BaseFormTypes.ts
  ui/src/types/globalConfig/entities.ts
  ui/src/types/globalConfig/globalConfig.ts
  ui/src/util/api.ts
  ui/src/util/searchUtil.test.ts
  ui/src/util/searchUtil.ts
  ui/yarn.lock
Labels: size/XXL
