Repository splunk/addonfactory-ucc-generator, pull requests merged in 2025-07, with the labels that each got.

#1787 refactor: remove kwargs from conf generation files
  splunk_add_on_ucc_framework/generators/conf_files/create_account_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_alert_actions_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_commands_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_eventtypes_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_restmap_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_searchbnf_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_server_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_settings_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_tags_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_web_conf.py
Labels: refactor, size/M

#1771 feat: ucc-gen validate command support
  docs/commands.md
  poetry.lock
  pyproject.toml
  splunk_add_on_ucc_framework/commands/validate.py
  splunk_add_on_ucc_framework/main.py
  tests/unit/commands/test_validate.py
Labels: enhancement, size/L

#1814 test: fix `valid_config_logging_with_user_defined_handler.json`
  tests/unit/generators/conf_files/test_create_restmap_conf.py
  tests/unit/testdata/valid_config_logging_with_user_defined_handlers.json
Labels: bug, size/XS

#1812 feat(modify field on value): support regexp expresion
  docs/entity/modifyFieldsOnValue.md
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  ui/src/components/FormModifications/FormModifications.test.tsx
  ui/src/components/FormModifications/FormModifications.ts
  ui/src/components/FormModifications/TestConfig.ts
  ui/src/types/globalConfig/baseSchemas.ts
Labels: size/L

#1815 docs: fix rest_handlers documentation
  docs/options/rest_handlers.md
Labels: size/S

#1790 fix: Jinja2 vulnerability
  .github/workflows/build-test-release.yml
  splunk_add_on_ucc_framework/commands/modular_alert_builder/alert_actions_py_gen.py
Labels: size/XS

#1793 refactor: replace general xml.etree import with specific modules
  .github/workflows/build-test-release.yml
  splunk_add_on_ucc_framework/data_ui_generator.py
Labels: size/M

#1800 feat: update recursive_overwrite method to merge .conf files
  splunk_add_on_ucc_framework/utils.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/web.conf
  tests/testdata/expected_addons/expected_output_no_global_config/Splunk_TA_UCCExample/default/props.conf
  tests/testdata/test_addons/package_global_config_everything/package/default/restmap.conf
  tests/testdata/test_addons/package_global_config_everything/package/default/web.conf
  tests/testdata/test_addons/package_no_global_config/package/default/props.conf
Labels: size/L

#1810 feat(oauth): allow different components
  splunk_add_on_ucc_framework/schema/schema.json
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/splunk_ta_uccexample_account.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/ui/pages/account_page.py
  tests/ui/test_configuration_page_account_tab.py
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/BaseFormView/BaseFormViewUtils.ts
  ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
  ui/src/components/CustomControl/CustomControlBase.ts
  ui/src/components/EntityModal/EntityModal.test.tsx
  ui/src/components/EntityModal/TestConfig.ts
  ui/src/types/components/BaseFormSharableTypes.ts
  ui/src/types/components/BaseFormTypes.ts
  ui/src/types/components/CustomHookBase.ts
  ui/src/types/globalConfig/entities.ts
  ui/src/types/globalConfig/oAuth.ts
Labels: size/XL

#1811 refactor: eval() to function
  ui/src/util/Validator.ts
  ui/src/util/tests/parseFunction.test.tsx
  ui/src/util/tests/validators.test.ts
Labels: size/L

#1796 feat: added footer component
  docs/metadata.md
  splunk_add_on_ucc_framework/schema/schema.json
  ui/.storybook/withSplunkTheme.tsx
  ui/src/components/Footer/Footer.test.tsx
  ui/src/components/Footer/Footer.tsx
  ui/src/components/Footer/stories/Footer.stories.tsx
  ui/src/components/Footer/stories/__images__/Footer-base-chromium.png
  ui/src/components/SubDescription/stories/__images__/SubDescription-base-chromium.png
  ui/src/pages/AppProviders.tsx
  ui/src/pages/Dashboard/utils.tsx
  ui/src/pages/GlobalStyles.ts
  ui/src/pages/stories/__images__/GlobalConfigPlayground-global-config-playground-chromium.png
  ui/src/types/globalConfig/meta.ts
Labels: size/L

#1816 refactor: update writer logic
  splunk_add_on_ucc_framework/generators/conf_files/create_account_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_alert_actions_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_app_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_commands_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_eventtypes_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_restmap_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_searchbnf_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_server_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_settings_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_tags_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_web_conf.py
  splunk_add_on_ucc_framework/generators/file_generator.py
  splunk_add_on_ucc_framework/generators/html_files/create_alert_actions_html.py
  splunk_add_on_ucc_framework/generators/python_files/create_custom_command_python.py
  splunk_add_on_ucc_framework/generators/xml_files/create_configuration_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_dashboard_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_default_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_inputs_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_redirect_xml.py
  splunk_add_on_ucc_framework/templates/conf_files/alert_actions_conf.template
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/alert_actions.conf
  tests/unit/generators/conf_files/test_create_account_conf_spec.py
  tests/unit/generators/conf_files/test_create_alert_actions_conf.py
  tests/unit/generators/conf_files/test_create_app_conf.py
  tests/unit/generators/conf_files/test_create_commands_conf.py
  tests/unit/generators/conf_files/test_create_eventypes_conf.py
  tests/unit/generators/conf_files/test_create_inputs_conf.py
  tests/unit/generators/conf_files/test_create_restmap_conf.py
  tests/unit/generators/conf_files/test_create_searchbnf_conf.py
  tests/unit/generators/conf_files/test_create_server_conf.py
  tests/unit/generators/conf_files/test_create_settings_conf.py
  tests/unit/generators/conf_files/test_create_tags_conf.py
  tests/unit/generators/conf_files/test_create_web_conf.py
  tests/unit/generators/html_files/test_create_alert_actions_html.py
  tests/unit/generators/python_files/test_create_custom_command_python.py
  tests/unit/generators/test_file_generator.py
  tests/unit/generators/xml_files/test_create_configuration_xml.py
  tests/unit/generators/xml_files/test_create_dashboard_xml.py
  tests/unit/generators/xml_files/test_create_default_xml.py
  tests/unit/generators/xml_files/test_create_inputs_xml.py
  tests/unit/generators/xml_files/test_create_redirect_xml.py
  tests/unit/helpers.py
Labels: size/XXL

#1839 fix: path issue for default alerticon
  splunk_add_on_ucc_framework/generators/file_generator.py
  tests/smoke/test_ucc_build.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/alert_actions.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/alerticon.png
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample/modalert_test_alert_default_helper.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/test_alert_default.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/alert_actions.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/data/ui/alerts/test_alert_default.html
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/eventtypes.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/tags.conf
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
Labels: size/L

#1844 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/S

#1829 feat: add self param to stream_events and validate_input at build-time
  docs/inputs/helper.md
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/templates/input.template
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/example_input_two.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/helper_two.py
  tests/testdata/test_addons/package_global_config_everything/package/bin/helper_two.py
  tests/unit/commands/test_build.py
  tests/unit/testdata/package/bin/example_helper.py
  tests/unit/testdata/package/bin/example_helper_no_stream_events.py
  tests/unit/testdata/package/bin/example_helper_not_callable.py
Labels: size/L

#1852 chore: update validation of placeholder usage
  splunk_add_on_ucc_framework/global_config_update.py
  splunk_add_on_ucc_framework/global_config_validator.py
  tests/unit/test_global_config_update.py
  tests/unit/test_global_config_validator.py
Labels: size/L

#1846 test: fix check global config unit test case
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/commands/package.py
  splunk_add_on_ucc_framework/global_config_update.py
  splunk_add_on_ucc_framework/global_config_validator.py
  tests/unit/test_check_globalConfig.py
  tests/unit/test_global_config_update.py
  tests/unit/test_global_config_validator.py
  tests/unit/testdata/invalid_config_placeholder_usage.json
Labels: bug, size/L

#1853 chore: merge develop into main
  docs/inputs/helper.md
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/commands/package.py
  splunk_add_on_ucc_framework/generators/conf_files/create_account_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_alert_actions_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_app_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_commands_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_eventtypes_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_restmap_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_searchbnf_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_server_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_settings_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_tags_conf.py
  splunk_add_on_ucc_framework/generators/conf_files/create_web_conf.py
  splunk_add_on_ucc_framework/generators/file_generator.py
  splunk_add_on_ucc_framework/generators/html_files/create_alert_actions_html.py
  splunk_add_on_ucc_framework/generators/python_files/create_custom_command_python.py
  splunk_add_on_ucc_framework/generators/xml_files/create_configuration_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_dashboard_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_default_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_inputs_xml.py
  splunk_add_on_ucc_framework/generators/xml_files/create_redirect_xml.py
  splunk_add_on_ucc_framework/global_config_update.py
  splunk_add_on_ucc_framework/global_config_validator.py
  splunk_add_on_ucc_framework/templates/input.template
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/example_input_two.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/helper_two.py
  tests/testdata/test_addons/package_global_config_everything/package/bin/helper_two.py
  tests/unit/commands/test_build.py
  tests/unit/generators/conf_files/test_create_account_conf_spec.py
  tests/unit/generators/conf_files/test_create_alert_actions_conf.py
  tests/unit/generators/conf_files/test_create_app_conf.py
  tests/unit/generators/conf_files/test_create_commands_conf.py
  tests/unit/generators/conf_files/test_create_eventypes_conf.py
  tests/unit/generators/conf_files/test_create_inputs_conf.py
  tests/unit/generators/conf_files/test_create_restmap_conf.py
  tests/unit/generators/conf_files/test_create_searchbnf_conf.py
  tests/unit/generators/conf_files/test_create_server_conf.py
  tests/unit/generators/conf_files/test_create_settings_conf.py
  tests/unit/generators/conf_files/test_create_tags_conf.py
  tests/unit/generators/python_files/test_create_custom_command_python.py
  tests/unit/generators/test_file_generator.py
  tests/unit/generators/xml_files/test_create_configuration_xml.py
  tests/unit/generators/xml_files/test_create_dashboard_xml.py
  tests/unit/generators/xml_files/test_create_default_xml.py
  tests/unit/generators/xml_files/test_create_inputs_xml.py
  tests/unit/generators/xml_files/test_create_redirect_xml.py
  tests/unit/test_check_globalConfig.py
  tests/unit/test_global_config_update.py
  tests/unit/test_global_config_validator.py
  tests/unit/testdata/invalid_config_placeholder_usage.json
  tests/unit/testdata/package/bin/example_helper.py
  tests/unit/testdata/package/bin/example_helper_no_stream_events.py
  tests/unit/testdata/package/bin/example_helper_not_callable.py
Labels: size/XL

#1854 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/S

#1861 test: 100% unit test coverage for generators
  splunk_add_on_ucc_framework/generators/conf_files/create_alert_actions_conf.py
  splunk_add_on_ucc_framework/generators/python_files/create_custom_command_python.py
  tests/unit/generators/conf_files/test_create_alert_actions_conf.py
  tests/unit/generators/conf_files/test_create_inputs_conf.py
  tests/unit/generators/conf_files/test_create_settings_conf.py
  tests/unit/generators/python_files/test_create_custom_command_python.py
  tests/unit/generators/test_file_generator.py
  tests/unit/generators/xml_files/test_create_default_xml.py
  tests/unit/testdata/valid_config_all_alerts.json
Labels: tests, size/L

#1865 chore: wait for corret console error in test
  ui/src/components/table/tests/CustomTableCell.test.tsx
Labels: size/S
