Repository splunk/addonfactory-ucc-generator, pull requests merged in 2025-06, with the labels that each got.

#1766 fix: handling of non external custom elements
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/splunk_ta_uccexample_account.conf.spec
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/custom/amdCustomHook.js
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/custom/amdCustomInputCell.js
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/custom/amdCustom_control.js
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/custom/amdCustom_input_row_replace.js
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_custom_amd_row_tab.py
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/app.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/restmap.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/server.conf
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/web.conf
  tests/testdata/test_addons/package_global_config_everything/globalConfig.json
  tests/testdata/test_addons/package_global_config_everything/package/appserver/static/js/build/custom/amdCustomHook.js
  tests/testdata/test_addons/package_global_config_everything/package/appserver/static/js/build/custom/amdCustomInputCell.js
  tests/testdata/test_addons/package_global_config_everything/package/appserver/static/js/build/custom/amdCustom_control.js
  tests/testdata/test_addons/package_global_config_everything/package/appserver/static/js/build/custom/amdCustom_input_row_replace.js
  tests/testdata/test_addons/package_global_config_everything/package/default/restmap.conf
  tests/testdata/test_addons/package_global_config_everything/package/default/web.conf
  tests/ui/test_configuration_page_account_tab.py
  ui/src/components/BaseFormView/BaseFormView.tsx
  ui/src/components/CustomControl/CustomControl.tsx
  ui/src/components/CustomMenu/CustomMenu.tsx
  ui/src/components/CustomTab/CustomTab.tsx
  ui/src/components/table/CustomTableCell.tsx
  ui/src/components/table/CustomTableControl.tsx
  ui/src/components/table/CustomTableRow.tsx
  ui/src/types/modules.d.ts
  ui/src/util/script.ts
Labels: size/XL

#1765 chore: context component cleanup
  ui/package.json
  ui/src/components/table/CustomTableCell.tsx
  ui/vite.config.ts
  ui/yarn.lock
Labels: size/XXL

#1776 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XXL

#1788 chore: use spaces instead of tabs for HTML templates
  splunk_add_on_ucc_framework/templates/html_templates/alert_html_skeleton.template
  splunk_add_on_ucc_framework/templates/html_templates/checkbox.html
  splunk_add_on_ucc_framework/templates/html_templates/dropdownlist_splunk_search.html
  splunk_add_on_ucc_framework/templates/html_templates/radio.html
  splunk_add_on_ucc_framework/templates/html_templates/text.html
  splunk_add_on_ucc_framework/templates/html_templates/textarea.html
  tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/data/ui/alerts/test_alert.html
Labels: refactor, size/L

#1775 refactor: added new layout for runtime error
  ui/src/components/ErrorBoundary/ErrorBoundary.style.ts
  ui/src/components/ErrorBoundary/ErrorBoundary.test.tsx
  ui/src/components/ErrorBoundary/ErrorBoundary.tsx
  ui/src/components/ErrorBoundary/stories/ErrorBoundary.stories.tsx
  ui/src/components/ErrorBoundary/stories/__images__/ErrorBoundary-base-chromium.png
  ui/src/pages/Configuration/tests/ConfigurationPage.test.tsx
Labels: size/L

#1777 test: fix flaky test 6
  tests/ui/test_configuration_page_account_tab.py
Labels: size/XS

#1795 feat(dashbaord): do not build dashboard files when no need
  splunk_add_on_ucc_framework/commands/build.py
  splunk_add_on_ucc_framework/utils.py
  tests/smoke/test_ucc_build.py
Labels: size/M

#1798 chore: merge main into develop
  NOTICE
  docs/CHANGELOG.md
  pyproject.toml
  splunk_add_on_ucc_framework/__init__.py
  ui/package.json
Labels: size/XXL

#1805 feat(textarea): mask data when encrypted
  ui/src/components/TextAreaComponent/TextAreaComponent.tsx
  ui/src/components/TextAreaComponent/stories/TextAreaComponent.stories.tsx
  ui/src/components/TextAreaComponent/stories/__images__/TextAreaComponent-encrypted-chromium.png
  ui/src/components/TextAreaComponent/stories/__images__/TextAreaComponent-un-encrypted-chromium.png
Labels: size/M

#1808 test: specify pyparser version which is supported by python 3.7
  tests/testdata/test_addons/package_global_config_everything/package/lib/requirements.txt
Labels: size/XS
